src/dso_api/datasets/models.py, src/tests/files/afval.json, src/tests/files/bommen.json
Amsterdam schema now has a mandatory "display" property on the table. Start using it.
=> Start using display field from amsterdam schema.

src/dso_api/dynamic_api/filterset.py, src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/views.py, src/dso_api/urls.py, src/rest_framework_dso/filters.py, src/rest_framework_dso/openapi.py, src/tests/conftest.py, src/tests/test_openapi.py, src/tests/test_rest_framework_dso/models.py, src/tests/test_rest_framework_dso/test_filters.py, src/tests/test_rest_framework_dso/test_views.py
- Added [lt], [lte], [gt], [gte], [in] operators.
- Fixed using FOREIGNKEY_id field for filters (by using attname).
- Fixed OpenAPI types for FK parameters.
- Fixed OpenAPI types for geometry fields.
- Fixed OpenAPI types for _links field.
- Avoid value checks for IN fields (may pass non-existing values)
=> [DS-232] Allow filtering with lookup operators

src/dso_api/dynamic_api/app_config.py, src/dso_api/dynamic_api/routers.py, src/requirements.in, src/requirements.txt, src/tests/conftest.py
This PR is adding VirtualAppConfigs, allowing django to think that all of Dynamic Models belong to real apps.
All of this is needed to allow models with same name being registered in django apps registry (to allow relations to resolve).
Alternative is to prefix all models with Dataset.id, but I'm afraid it will turn into much bigger mess.
But first: https://github.com/Amsterdam/schema-tools/pull/21
=> Fixing crash on load due to duplicate Model names.

src/dso_api/dynamic_api/remote/serializers.py, src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/utils.py, src/requirements.in, src/requirements.txt
The api of slugify has changed, kwarg "sign" -> "separator"
So schematools 0.7.0 is needed, because that version has the same
new dependency
=> Upgrade python-string-utils pinning to 1.0.0

src/dso_api/urls.py, src/rest_framework_dso/views.py
When multiple trailing slashes are added to the endpoint it raises a 404 error. This is replaced by a custom error message in JSON stating that multiple trailing slashes are not supported to guide the user to correct the error.
Resolves: DS-281
=> [DS-281] Multiple trailing slashes not supported

src/dso_api/dynamic_api/middleware.py, src/dso_api/settings.py
Addition of `dataset` to every request will make filtering/limiting output based on Schema specification easier.
To  be used by both Historical API and Embeded relations.
=> Make life easier, add `dataset` to every request.

src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/urls.py, src/dso_api/dynamic_api/views.py, src/requirements.in, src/requirements.txt
Very minimal csv download implementation.
Uses rest-pandas. Added view to download the full dataset as csv. 
Is still incomplete, no filtering. Permissions are enable, needs testing.
Some dirty hack needed to silence  drf_spectacular (openapi)
=> Csv support

src/dso_api/settings.py
Extra allowed headers, nodig voor preflight calls vanaf dataportaal (verzoek Jon Koops)
=> Add allow headers for Crs, to accomodate preflight calls

src/dso_api/dynamic_api/serializers.py, src/requirements.in, src/requirements.txt, src/tests/conftest.py, src/tests/files/bagh.json, src/tests/files/vestiging.json, src/tests/test_dynamic_api/test_serializers.py
For example stadsdelen ipv stadsdeel
Also remove test for model name that is always equal
=> Make is possible to choose a name for backwards relations.

src/rest_framework_dso/utils.py, src/tests/test_rest_framework_dso/test_serializers.py
API would crash into `KeyError` if relation is not found (`BAG` relations inside `meetbouten` as example).
=> Fixing error with embedding non-existing relations.

src/dso_api/dynamic_api/fields.py, src/dso_api/dynamic_api/utils.py, src/requirements.in, src/tests/test_dynamic_api/test_fields.py
GOB uses ".", we already introduced "_" in bagh dataset.
Should be merged into one approach in the future.
=> Use two different split chars

src/dso_api/dbrouters.py, src/dso_api/settings.py, src/tests/test_database_schemas_router.py
Use Postgresql Schemas for datasets.
Currently set up to use `settings.DATABASE_SCHEMAS` variable, so we do not have to store this sensitive data in amsterdam-schema.
Expands across multiple postgres schemas/datasets work fine.
=> Postgres schemas

.gitignore, src/dso_api/dynamic_api/app_config.py, src/dso_api/dynamic_api/fields.py, src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/serializers.py, src/rest_framework_dso/fields.py, src/rest_framework_dso/serializers.py, src/rest_framework_dso/utils.py, src/tests/conftest.py, src/tests/files/gebieden.json, src/tests/files/meldingen.json, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views.py, src/tests/test_rest_framework_dso/models.py
Er is een custom Django model-veld geintroduceerd (in schema-tools) dat een 'losse' relatie kan leggen naar een temporele dataset (alleen obv de 'identificatie'). In de DSO is een mapping naar een DRF-type veld gemaakt voor dit Django model veld.
Dit zorgt voor het construeren van de juiste urls.
Verder is geregeld dat dit type velden ook werkt bij gebruik in een 'expand' en dat evt. temporele hyperlinks binnen de 'expanded' objecten ook weer correct worden geconstrueerd.
=> Add loose relation field and make it work for expand

src/dso_api/settings.py
This does not work with the CORS setting by HAProxy : Access-Control-Allow-Credentials: true
Now the Access-Control-Allow-Origin will be set by HAProxy to the Origin
in the request. Then it will work correcly with the other CORS settings
=> Remove wildcard setting for Access-Control-Allow-Origin: *

src/requirements.in, src/requirements.txt
For events, extra temporal fields have been introduced in the
dynamic schemas. However, these fields are not yet in the
postgresql tables. First downgrade to avoid these issues
in production.
=> Downgrade schema-tools to fix issue with missing temporal fields

src/dso_api/dynamic_api/filterset.py, src/requirements.in, src/requirements.txt, src/tests/files/parkeervakken.json
The definition of filtersets in amsterdam schema was changed.
However, this was done for a test and the implementation in the filters.
So, existing datasets were crashing (at django startup).
The schema change was not very sensible, introducing a "kwargs" keyword
in amsterdam schema and using (and being dependent on) snake_case attributes.
So, this change has been reverted.
=> Revert filterset change

src/dso_api/dynamic_api/serializers.py, src/tests/test_dynamic_api/test_views_api.py
Since loose FK fields are transformed into links wrapped in a HAL envelope, the value of the original field "disappeard". With this fix, the original field is included in the body of the object as a char field, while also keeping the `_links` references as before.
- Changed the type of the loose FK field into CharField for simple rendering in the body serializer.
- Updated two pytests with the additional field.
=> Keep loose FK verbatim in body

src/dso_api/settings.py
Bag will be imported in the masterdb.
Use the 'bag' name for the data that previously was coming from bag_v11
=> Remove bag_v11_read useage

src/dso_api/dynamic_api/middleware.py
Fixes attribute errors related to `TemporalDatasetMiddleware` not setting `dataset_temporal_slice` as expected.
Sentry stack: https://sentry.data.amsterdam.nl/sentry/datapunt-apis-acc/issues/2679358/?environment=dso-api&referrer=alert_email
=> Fix attribute errors from fields for non-temporal datasets.

src/rest_framework_dso/response.py, src/tests/test_dynamic_api/test_views_api.py
The response headers were already determined before reading the streaming
content.
=> Fix content-type on streaming responses, which is determined too late

src/dso_api/dynamic_api/middleware.py, src/dso_api/dynamic_api/oas3.py, src/dso_api/dynamic_api/remote/views.py, src/dso_api/dynamic_api/serializers.py, src/rest_framework_dso/renderers.py, src/rest_framework_dso/serializers.py, src/rest_framework_dso/views.py
The original DRF `Serializer.fields` is a cached_property that reads get_fields() once.
Thus overriding `get_fields()` instead of `fields` preserves this caching.
Currently the fields were read multiple times per object, while doing massive unauthorized-fields checks.
This change fixes that.
To address any concerns about information-leakage serializers *must* receive an request object so the unauthorized field checks are performed. This only conflicted with the OAS schema view, which is fixed by `public=False`. Assigning request.auth_profile had to be moved because of this.
The CSV export can not also avoid reading all fields (including M2M), while not returning these.
=> Massive performance fix of serializer.fields access.

src/dso_api/dynamic_api/remote/views.py, src/dso_api/settings.py
Explicit filter kadastrale objecten for natuurelijk persoon if not
BRK/RSN.
Use schema only for validation of response, but return complete
HaalCentraal response
<Please fill information>
=> Use certificate for production HaalCentraal

src/rest_framework_dso/serializers.py
In the production version for HaalCentraal brk the begrenzingPerceel is
missing. This now gives the following error:
https://sentry.data.amsterdam.nl/sentry/datapunt-apis-prod/issues/2680654/
=> Do not give key error for missing geofield if is not required.

docs/source/generic/rest.rst, docs/source/generic/temporele_datasets.rst, docs/source/generic/wfs.rst
* Omit default page size
Doesn't match the implementation, and is prone to change anyway.
* Explain wildcard syntax
* Warn about trailing slash when using QGIS
Omitting the trailing slash causes QGIS to not work, only emitting
cryptic warning messages in its OAFIP log (whatever that may be).
* Fixed links in temporele datasets
bagh/buurt become gebieden/buurten.
=> Fixes to API docs (docs/ dir)

src/dso_api/dynamic_api/fields.py, src/requirements.in, src/requirements.txt, src/tests/test_dynamic_api/test_temporal_actions.py
When using url params like _format=json, the embedded
temporal urls were having  more than one '?' in the url, leading to invalid url.
Fix invalid temporal url in the "_links" section of the HAL output.
=> Fix problem with multiple ? in urls

README.md, src/dso_api/dynamic_api/routers.py, src/dso_api/settings.py, src/tests/test_dynamic_api/test_router.py
Router loading mechanics, allowing limitation of datasets loaded into memory using `DATASETS_LIST` and/or `DATASETS_EXCLUDE` environment variables.
Can be used to split APIs with sensitive information from generic APIs on infrastructure level.
=> DS-597. Limit datasets with DATASETS_LIST and DATASETS_EXCLUDE

src/rest_framework_dso/views.py, src/tests/test_rest_framework_dso/test_views.py
Fix sentry message for `_expand=fieldname`.
The orjson library doesn't render gettext_lazy() messages. While it's possible to insert a _default hook, the source is well-defined and fixable.
* Tests added.
* A related set of tests is indented for grouping.
=> Fix exception rendering for invalid _expand, due to gettext_lazy()

src/dso_api/dynamic_api/fields.py, src/dso_api/dynamic_api/serializers.py, src/rest_framework_dso/fields.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_temporal_actions.py, src/tests/test_dynamic_api/test_views_api.py
Temporal identifier fields (usually named `identificatie` and `volgnummer`) are moved into the HAL envelope.
Specifically, this means:
- Identifier fields are removed from the body (potentially a breaking change)
- Identifier fields are added to `self` in `_links`
- Identifier fields are added to the HAL envelope of temporal relations (besides `href` and `title`)
- In case of loose relations, only `identificatie` (name of identifier fieldname in the related dataset) is added to the relation HAL envelope. (`volgnummer` is only shown in the embedded objects with `_expand=true`. Same as before, but:
- In case of embedding, temporal identifier fields are added to `self` in `_links` for each embedded object.
=> extension of hal envelope of relations

src/rest_framework_dso/renderers.py, src/tests/test_rest_framework_dso/test_views.py
Fixes the browsable API to show the expand field contents.
=> Fix empty generator content in the browsable API preview.

src/dso_api/dynamic_api/filterset.py, src/tests/test_rest_framework_dso/models.py, src/tests/test_rest_framework_dso/test_filters.py
This patch adds the isnull, not, isempty and like filters to URL fields.
Fixes DS-501, which asks for these fields, except like. I could have dropped like, but it comes for free with the string filterset and it can be useful for finding, e.g., non-HTTPS URLs (`?url[like]=http:*`).
Has a unit test and works with a local copy of the bekendmakingen dataset.
=> Add string filterset to URLs

docs/source/generic/rest.rst, src/dso_api/dynamic_api/views/api.py, src/rest_framework_dso/filters.py, src/rest_framework_dso/serializers.py, src/tests/test_rest_framework_dso/test_filters.py, src/tests/test_rest_framework_dso/test_serializers.py
`_field=-foo,-bar` now causes all fields to be returned except for foo and bar.
Combining positive and negative mentions in the fields list is not allowed.
=> [DS-317] Allow negative field specifiers

src/dso_api/dynamic_api/views/wfs.py, src/tests/conftest.py, src/tests/files/afval.json, src/tests/test_dynamic_api/test_views_wfs.py
The use of underscore - as a result of camelCase table names - was not taken into account when building the WFS viewset.
This led to a 400 Bad Request error. Which was a result of not finding the table in the internal models due to the ignore of table names with underscores.
DSO-API WFS view
N.A.
N.A.
N.A.
=> FIX using camelCase table names vs feature names in WFS

src/dso_api/dynamic_api/fields.py, src/dso_api/dynamic_api/filterset.py, src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/utils.py, src/tests/test_dynamic_api/test_views_api.py
This code was obscuring a problem, as the schematools package generated additional "related" fields for objects that aren't temporaral (e.g. bag.panden.heeftDossier_dossier).  That logic should only be triggered for "identificatie" and "volgnummer".
Also, the string matching done here is extremely brittle and could easily remove other fields from the response. Which it did, as it completely broke the CSV inline fields for embedding relations.
Partially reverts 2dfdf75
=> Revert part of PR #209 - the fields removal logic was too aggressive

src/dso_api/dynamic_api/permissions.py, src/tests/test_dynamic_api/test_views_api.py
In the permissions.py the method `fetch_scopes_for_dataset_table` used the table id  - as specified in the JSON schema - as lookup value for DatasetTable object to get the objects auth attribute. Due to camelCase the object could not be found. 
The object was present in it's snake_case format. As a fix the lookup was added with a snake_case translation. 
In the future a general approach of using snake_case and camelCase in the dso-api logic could be revisited.
permissions.py, fetch_scopes_for_dataset_table method
N.A.
N.A.
N.A.
=> bug fix AUTH specification on table

src/requirements.in, src/requirements.txt, src/rest_framework_dso/embedding.py, src/rest_framework_dso/serializers.py, src/tests/test_rest_framework_dso/test_embedding.py
This performs prefetches in batches, leveraging Django's prefetch_related_objects() while using QuerySet.iterator() for performance.
As extra feature, the previously prefetched objects are reused so the next batch doens't have to refetch identical related objects.
=> Optimize querysets, allow prefetch-related on large sets

src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/views/api.py, src/tests/test_dynamic_api/test_serializers.py
The links_serializer=True check is moved into a `links_serializer_factory()`. Likewise, `_build_serializer_field()` is split into separate methods for relations. This fixes the code complexity issues.
The new separate code paths avoids building unnecessary fields for the _links serializer or "body serializer" part that would later be removed in get_fields(). This improves upon the work in #209 / 2dfdf75. The field removal logic is still preserved, as it's used for some situations like detail vs list view.
Misc:
* Removed 'depth' testing as that was always true, when testing on other variables early.
* Removed usage of internal _table_schema variables.
=> cleanup serializer_factory logic, same code flow but more readable

src/dso_api/dynamic_api/remote/serializers.py, src/rest_framework_dso/embedding.py, src/rest_framework_dso/fields.py, src/rest_framework_dso/renderers.py, src/rest_framework_dso/serializers.py, src/tests/conftest.py, src/tests/files/bag.json, src/tests/test_dynamic_api/test_views_api.py
The `DSOSerializer` incorporates the embedded-field serializers as regular fields when the output format needs to use inline embedding (e.g. for CSV). To make this performant, the prefetch was optimized in #216 (5e4b9f18f567f3ffddd2a2ccedeb86e6e5ee0515).
The serializer construction is improved to handle sub-resources well, and to avoid expanding their parameters. The many=True is needed to properly initialize inline M2M fields for an output renderer.
All output renderers can declare whether they support "inline" embeds, and whether the support M2M relations.
=> CSV expand support

src/rest_framework_dso/filters.py
The get_ordering method assumed it could pass empty identifiers to to_snake_case, which in the latest version refuses to convert those.
=> Fix DSOOrderingFilter's snake-casing

src/rest_framework_dso/fields.py, src/rest_framework_dso/renderers.py, src/tests/test_dynamic_api/test_views_api.py
This PR is to solve some differences between the WFS and DSO API output.
It also allows to distinguish between normal and additionally returned objects when `?_embed=true` or `?_embedScope=..` is used.
=> Include a GeoJSON id in the output, similar to what the WFS server does.

src/rest_framework_dso/renderers.py, src/rest_framework_dso/views.py, src/tests/test_dynamic_api/test_views_api.py
Add content-disposition header for csv and geojson download.
For a more user-friendly behaviour when downloading in the browser
Filename of the download is constructed based on {dataset_id}-{table_id}-{timestamp} if available.
=> Add content-disposition header for csv and geojson

src/dso_api/dynamic_api/permissions.py, src/tests/test_dynamic_api/test_views_wfs.py
Permissions checks. HasOAuth2Scopes assumes it deals with DRF classes, but DatasetWFSView isn't one so it crashes with an AttributeError/HTTP 500 instead of 403.
=> WFS unauthorized gives 500 -> give 403

src/dso_api/dynamic_api/remote/views.py, src/tests/conftest.py, src/tests/test_dynamic_api/remote/test_views.py
URL creation in `RemoteViewSet`. It now works with or without trailing slash and is properly tested.
=> Make URL creation in RemoteViewSet more robust

README.md, integration_test/test_hcbrk.py
This adds a small integration test for HC-BRK (Kadaster), using the example output produced by the Kadaster API. It can be run using pytest.
I wasn't sure whether to put this in `src` or at toplevel. Thoughts?
=> Integration test for HC-BRK

src/tests/conftest.py, src/tests/files/geometry_auth.json, src/tests/test_dynamic_api/test_views_mvt.py
MVT tests. This is the first step toward getting authorization scopes from the schema instead of the models.
=> Get auth scopes from schema in MVT tests

src/tests/files/geometry_auth.json, src/tests/test_dynamic_api/test_views_mvt.py
Authorization tests. The MVT test now requires two scopes to access the geometry field.
=> Test multiple required scopes in MVT auth test

README.md
The README explains only the complicated way of testing with custom schemas. Mention the simple way first and condense the instructions for the nginx container.
=> Point out import_schemas first in README

src/tests/conftest.py, src/tests/files/geometry_authdataset.json, src/tests/test_dynamic_api/test_views_wfs.py
WFS authorization tests now use schemas instead of a model that is modified on the fly. Follow-up to #255.
=> Run WFS auth tests on custom schemas

Dockerfile-dev-docs, DockerfileDevDocs, Jenkinsfile, docker-compose.yml
Automated build of dev docs.
It also includes building of image using jenkins, making it ready to deploy docs to publicly accessible location.
What needs to be done in the future:
- Deployment should be done via OpenStack.
However if starting `docker-compose up dev-docs` you will be able to see docs, which makes me wonder: do we need these docs served somewhere on amsterdam.nl?
=> Build dev docs and run them locally in docker.

src/dso_api/dynamic_api/permissions.py, src/tests/files/geometry_auth.json, src/tests/files/geometry_authdataset.json, src/tests/test_dynamic_api/test_views_mvt.py, src/tests/test_dynamic_api/test_views_wfs.py
"auth" fields on datasets, tables and fields could previously be comma-separated lists stored in JSON strings (`"FOO/BAR,FOO/BAZ"`). This feature was never used and is now removed.
=> Remove comma-separated "auth" list support

dev-docs/source/auth.rst
The dev-docs incorrectly describe the scope checking as performing an AND of scopes at different levels. That turns out to be false. Only the highest-level scopes are checked.
Also, the dev-docs were kind of fuzzy about the exact workings of profiles. This explains them in some more detail wrt. requests, scopes and schemas. The "statistician" example now explains exactly how schemas fall short (lack of an OR operator, really).
In the example, I've replaced "encoded" by "read" because "encoded" isn't actually implemented in dso-api.
=> Fix dev-docs about authorization, again

src/dso_api/dynamic_api/openapi.py, src/dso_api/dynamic_api/routers.py, src/rest_framework_dso/openapi.py, src/tests/files/afval.json, src/tests/test_openapi.py
Changed *dataset_ids to actual 'dataset' object as this is already known at construction and avoids fetching the object again during rendering.
=> Pass title/description/version/license from Amsterdam Schema to the OpenAPI docs

dev-docs/source/api/rest_framework_dso.filters.rst, docs/source/_templates/datasets/dataset.rst.j2, docs/source/datasets.py, docs/source/generic/rest.rst, src/dso_api/dynamic_api/openapi.py, src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/urls.py, src/dso_api/dynamic_api/views/__init__.py, src/dso_api/dynamic_api/views/api.py, src/dso_api/dynamic_api/views/oauth.py, src/dso_api/settings.py, src/rest_framework_dso/embedding.py, src/rest_framework_dso/fields.py, src/rest_framework_dso/filters/__init__.py, src/rest_framework_dso/filters/backends.py, src/rest_framework_dso/filters/filtersets.py, src/rest_framework_dso/openapi.py, src/rest_framework_dso/serializers.py, src/rest_framework_dso/views.py, src/tests/test_openapi.py, src/tests/test_rest_framework_dso/test_filters.py
Veel fixes in de OpenAPI weergave.
Als je de root van een dataset opent (bijv.`/v1/bag/`) krijg je in de browser nu een swagger UI te zien. Hiermee is de browser ervaring voor `/v1/`, `/v1/dataset/` en `/v1/dataset/tabel/` allemaal een HTML weergave.
Daarnaast worden veel descriptions nu overgenomen, en krijgen filter-parameters weer het juiste data type.
=> OpenAPI fixes + Swagger op root

src/dso_api/dynamic_api/remote/clients.py, src/dso_api/dynamic_api/remote/views.py, src/dso_api/dynamic_api/routers.py, src/tests/test_dynamic_api/remote/test_views.py
This is a preliminary PR for HC-BRK authorization. The main functional change is that the HC-BRK endpoint no longer forwards its authorization token to the remote. Doing our own authentication is the next step.
=> Factor remote endpoint clients out of remote viewsets

src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/views/mvt.py, src/dso_api/dynamic_api/views/wfs.py
MVT and WFS used an overloaded `has_permission` method to do auth checks. They now call a custom method so the code paths are more clearly separated.
=> Separate MVT+WFS permissions checks from DRF checks

src/requirements.in, src/requirements.txt
I scanned the diffs for these and am reasonably sure nothing crazy happens.
pytest-django is not upgraded, since 4.3.0 causes a test failure:
```
――――――――――――――――――― ERROR at teardown of TestDatabaseSchemasRouter.test_db_for_read_returns_schema_name_if_set ――――――――――――――――――――
cls = <class 'pytest_django.fixtures._django_db_fixture_helper.<locals>.PytestDjangoTestCase'>
@classmethod
def tearDownClass(cls):
if cls._databases_support_transactions():
cls._rollback_atomics(cls.cls_atomics)
for conn in connections.all():
conn.close()
>       super().tearDownClass()
../venv/lib/python3.8/site-packages/django/test/testcases.py:1135:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
=> Bump some dependencies

src/dso_api/dynamic_api/middleware.py, src/dso_api/settings.py, src/tests/test_dynamic_api/test_views_api.py
Removing excessive request logging that is absolutely not needed.
=> Remove RequestAuditLoggingMiddleware.

.flake8
`flake8` has a default ignore list. Reason being that, according to its
maintainer on the podcast https://testandcode.com/156?t=230, PEP8 has
flip flopped on certain style recommendations over the years. So
`flake8` simply adds those to the default ignore list. In addition there
are number of style checks that are each other's opposite. These are
added to the default ignore list as well.
So when specifying your own `ignore` list these default values are
overwritten. Hence it's better to extend the ignore list by means of the
`extend-ignore` option. And that's what I'm doing in this commit.
BTW I'm removing the W503 rule. It's already part of the default ignore
list.
=> flake8: use extend-ignore instead of ignore.

src/dso_api/dynamic_api/remote/clients.py
Looks like the BRP endpoint doesn't understand the Accept header "application/json; charset=utf-8". Drop the charset from the header.
If JSON in any other encoding comes in, we'll have to decode it, but RFC 8259 (8.1) requires JSON to be in UTF8 anyway, except in a "closed ecosystem". I've never witnessed a system that uses any other encoding for JSON.
=> [AB#8005] RemoteClient: send Accept header without charset

src/rest_framework_dso/fields.py, src/rest_framework_dso/serializers.py
This fixes combining `_fields=..` with `_expandScope`.
This is a bit of a stop-gap to quickly fix errors for dataportaal devs.
This doesn't handle the second part yet (relation.field), but at least fixes the unwanted error message. The field parsing is already written in the same style as the expand logic so it can be revised to support nested field limiting too.
=> [AB#8346] Fix combining _fields with _expand parameters.

src/rest_framework_dso/filters/backends.py, src/tests/test_dynamic_api/test_filters.py
Wanneer je als gebruiker een incorrect punt opgeeft in de contains filter krijg je momenteel een non-descript error 500 melding terug. Deze pr zorgt dat een 400 error wordt terug gegeven, die aangeeft dat de geometrie niet klopt. ex: https://api.data.amsterdam.nl/v1/beschermdestadsdorpsgezichten/beschermdestadsdorpsgezichten/?geometry[contains]=121876,48774&_fields=status  (DS-520)
=> AB#4402 Fix error handling in geo contains filter

src/dso_api/dynamic_api/fields.py, src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/views/api.py, src/rest_framework_dso/fields.py
The temporal info has been move down from dataset to table.
The main temporal identifier, was still obtained from the dataset
that has now been corrected.
=> Use the identifier from the table_schema for temporality

docs/source/generic/rest.rst
The docs now say that the caller should send `Accept-Type: application/json`. The header is called `Accept` and sending `application/json` causes 406, because we want `application/hal+json` or `application/geo+json`.
=> AB#8005 Fix Accept header documentation

src/dso_api/dynamic_api/remote/clients.py, src/tests/test_dynamic_api/remote/test_views.py
Log client errors at error level.
Remove MKS header handling, it's not longer in use.
Return 401 or 403 from remote as 403. We previously returned 403 as 401 (by mistake) and returned 401 as 502 Bad Gateway.
=> AB#8005 Fix remote client error handling and logging

src/dso_api/dynamic_api/views/api.py
Csv, and geoJSON formats are available on the indexviews at
`/v1/`,`/v1/wfs/` and `/v1/mvt/`. The csv is badly parsed and
the geoJSON should not be available. This change, removes those
format options from the views. Leaving the json and api formats.
=> AB#11454 Restrict available formats in indexviews

src/dso_api/dynamic_api/middleware.py, src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/views/api.py, src/dso_api/dynamic_api/views/mvt.py, src/dso_api/dynamic_api/views/wfs.py, src/requirements.in, src/requirements.txt, src/tests/conftest.py, src/tests/test_dynamic_api/remote/test_views.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views_api.py, src/tests/test_dynamic_api/test_views_mvt.py, src/tests/test_dynamic_api/test_views_wfs.py, src/tests/utils.py
This uses the new schematools authorisation framework (more info there). Instead of basing authorisation on top of the exported data in Django models, the low-level schema objects are queried by a single integrated rule engine. The UserScopes object handles both the "auth" and "profile" rules.
This also removes the need to match on field-names. Instead the model fields have a direct reference back to the schema field.
Likewise, get_fields() can exclude fields directly now and apply transformations on a field-level instead of manipulating the dict afterwards.
=> Refactor authentication to use native schema objects (DSO-API part)

dev-docs/source/auth.rst
Update the documentation based on the auth refactor.
Also simplified some wording.
=> docs: update documentation on auth

docs/source/datasets.py
On request of datateam omgevingswet the presentation order of the tables within a dataset is not ordered on alphabet but on appearance within the Amsterdam schema specification. The order of the tables defined in the Amsterdam schema is based on a certain logical and intentional meaning. In respect of the self defined order of tables the datateams can use the docs more intuatieve.
v1/docs/
N.A.
N.A.
N.A.
=> API docs: order of tables are presented by order of appearance

docs/source/datasets.py
In addition to removing the alphabetical sort order for tables (within a dataset), also the alphabetical sort order for fields is removed. So it orders by the definition order in Amsterdam Schema. So the order is in line with the initial own logical order that the datateams specified in the schema.
v1/docs/
N.A.
N.A.
N.A.
=> No alphabetical sort order for fields.

src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/remote/views.py, src/tests/files/hcbrk.json, src/tests/test_dynamic_api/remote/test_views.py
Remote authorization is restored (currently, it's left entirely to the remote). Results of authorization checks are logged. Connection to HC-BRK is not yet established, but the parts are in place. In `tests/files`, there's a preliminary version of the detailed HC-BRK authorizing schema.
=> Restore remote authorization

src/dso_api/dynamic_api/serializers.py
_build_serializer_field called .get_field_schema() on AutoFields.
This caused a crash on startup. This commit fixes that bug.
=> Fix build serializer field for AutoField

src/rest_framework_dso/views.py
If an instance view returns a 404 or other http error
this will now display nicely in the page title and breadcrumbs
=> Breadcrumbs work with http errors

src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/urls.py, src/tests/test_openapi.py
The mvt and wfs views were not using the dataset.path
property yet. So datasets with subpaths appeared on
their old paths. This update fixes that.
MVT and WFS url pattern logic is moved from get_patterns
into the custom router. Because get_patterns doesnt work with
nested paths.
=> AB#5522 mvt and wfs views on sub paths

docs/requirements.txt, docs/source/datasets.py, src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/views/wfs.py, src/tests/test_openapi.py
The documentation was using the dataset name to create urls.
It now uses the dataset.path property like the rest of the application.
Also updates links to the docs in the index views.
=> Use new dataset urls in documentation

src/rest_framework_dso/pagination.py, src/tests/test_dynamic_api/test_views_api.py, src/tests/test_rest_framework_dso/test_serializers.py, src/tests/test_rest_framework_dso/test_views.py
Updates to _links in line with user story [11749](https://dev.azure.com/CloudCompetenceCenter/Data%20Diensten/_workitems/edit/11749)
* The 'self' field now includes query parameters. 
* The 'previous' and 'next' fields are only included when their links exist.
So 'previous' is not shown on page 1 and they are not shown on single page results, etc.
=> Yrob/ab11749 improve  _links

src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/serializers.py, src/rest_framework_dso/embedding.py, src/rest_framework_dso/fields.py, src/rest_framework_dso/serializers.py, src/rest_framework_dso/utils.py, src/rest_framework_dso/views.py, src/tests/conftest.py, src/tests/files/bag.json, src/tests/files/gebieden.json, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views_api.py
After increasing the number of allowed embedding, several bugs showed up. This PR also fixes those bugs.
* Added `ExpandScope` object that retains the nested embeds. Changed `fields_to_expand` to `expand_scope`, since the nested expand was lost by only passing `.keys()` to the sub-level serializer.
* Replaced `lru_cache()` with cachetools for `serializer_factory()`. This way the `nesting_level` no longer changes caching.
* Fixed recursion of the `serialize_factory()` for self-references, which avoided the LRU-cache.
* Completed BAG models for unit tests, so deep nesting could be tested.
=> Fix nested expand support, was broken after 2 levels

src/rest_framework_dso/renderers.py, src/tests/test_rest_framework_dso/test_views.py
Momenteel staat de HTML preview geen grote pagina’s toe. Dat deden we eerst omdat dit de server kon overbelasten. Nu de output streaming ingeladen wordt mag een grotere pagina nog wel, maar loopt de browser er waarschijnlijk in vast. Vandaar het compromis om alsnog een foutmelding te tonen.
=> Improve error message when using large pages in HTML view

src/dso_api/dynamic_api/openapi.py
Als een dastaset een leeg title veld heeft, wordt zn breadcrumb een lege string.
Deze commit  fixed dat.
=> AB#20567 Bugfix breadcrumbs work when dataset has empty title

src/.jenkins/owasp_vulnerability_scan/owasp_scan.py
Previously this worked without specify either `http://` or `https://`.
However after the upgrade to Python 3.9 this stopped working. Tried
looking whether this was caused by an upgraded dependency (`urllib3` or
`requests`) but couldn't find anything that might have caused this.
`urllib3` did add support for HTTPS proxies going from 1.25.x to 1.26.0.
Hence that seemed a plausible cause. But still couldn't find an exact
cause.
Note that `requests` documentation has stated for ages _that proxy URLs
must include the scheme_ hence our original usage in `owasp_scan` has
always faulty to begin with.
=> Provide URL schemes for proxy configs in owasp_scan.py

src/dso_api/dynamic_api/views/__init__.py, src/dso_api/dynamic_api/views/api.py, src/dso_api/dynamic_api/views/index.py, src/dso_api/dynamic_api/views/mvt.py, src/dso_api/dynamic_api/views/wfs.py, src/tests/test_dynamic_api/test_openapi.py, src/tests/test_dynamic_api/test_views_index.py
There were 2 test_openapi files and one had the api-root tests in them too. The "APIIndexView" is also a base class for many other dataset types, which really deserved to be in a separate file too.
=> Cleanup the merge of OpenAPI and API-index views and tests

src/dso_api/dynamic_api/serializers.py, src/rest_framework_dso/embedding.py, src/rest_framework_dso/fields.py, src/rest_framework_dso/serializers.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_temporal_actions.py, src/tests/test_dynamic_api/test_views_api.py
The implementation is done by tracking the primary-keys in the `id_list` and query the foreign table on a foreign key. It allowed to keep the existing machinery in place, which relies on streaming data by collecting object identifier's during the rendering.
This also changes the way embedded fields can be registered. In the end it wasn't required to build this, but it's still a good feature to have.
=> Implemented reverse embedding

src/rest_framework_dso/openapi.py, src/tests/test_dynamic_api/test_openapi.py
On the dataset overview page in openapi a
"No operations defined in spec!" message was shown where the endpoints should be, when user
was unauthorized. But schemas are public so endpoints should be visible.
This sets schema generator as_view_permissions() to always return true.
<Please fill information>
=> AB#21447 unauthorized dataset overview not visible

src/dso_api/dynamic_api/serializers.py, src/rest_framework_dso/embedding.py, src/rest_framework_dso/fields.py, src/tests/conftest.py, src/tests/files/gebieden.json, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_temporal_actions.py, src/tests/test_dynamic_api/test_views_api.py
Based on insights from reverse-embedded FK fields, the M2M implementation could be optimized. Before it queried the through table for *each* individual record to find related ID's. Now it collects a list of source ID's, and adjusts the query-filter to retrieve related objects in a single query. This also made the implementation of the reverse M2M very easy: the reverse ORM path has to be followed.
The old code also mixed up "identificatie" and "pk" fields, meaning that historical/temporal data likely wasn't returned at all. Tests also had this bug, and gave a false-negative after making changes. It turned out that the tested through table was incorrectly filled with non-existant IDs.
Additionally, repeated relations (forward/back/forward) became a problem. The serializers properly detect …
=> Implement reverse M2M embedded field and optimize querying.

src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/serializers.py
Now prints which model was being validated when a an app cannot be
found:
LookupError: No installed app with label 'bag'. (model = kadastraleobjecten)
=> Improve error message from routers._validate_model

src/dso_api/settings.py, src/tests/utils.py
These apps are not used at all, as the project doesn't need User models.
Nor do their tables have to be created.
=> Putting DSO-API on a diet: remove django.contrib.auth/contenttypes/messages

src/dso_api/dynamic_api/fields.py, src/dso_api/dynamic_api/middleware.py, src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/temporal.py, src/dso_api/dynamic_api/views/api.py, src/dso_api/settings.py, src/requirements.in, src/requirements.txt, src/rest_framework_dso/embedding.py, src/rest_framework_dso/serializers.py, src/tests/conftest.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_temporal_actions.py, src/tests/test_dynamic_api/test_views_api.py
Each commit holds a clear step for this PR.
* Removed lots of old code that was no longer used.
* Listings now return only active versions.
* Embeds also return active versions only.
* Test code lacked `beginGeldigheid` data, was added.
* Cleaned up test code URL construction (list vs detail)
=> Fixed listings and embedding to only return the right temporal records

src/dso_api/dynamic_api/remote/views.py, src/tests/files/haalcentraalbrk/dso_onroerendezaak_list.json, src/tests/files/haalcentraalbrk/hcbrk_onroerendezaak_list.json, src/tests/test_dynamic_api/remote/test_views.py
The part that belongs inside `_embedded.kadastraalonroerendezaken` was the entire output and the `_links` parts were missing, except for the `schema`, which was in the wrong place.
=> Fix output format of HC-BRK remote

src/tests/files/afval.json, src/tests/files/fietspaaltjes.json, src/tests/files/fietspaaltjes_no_display.json, src/tests/files/parkeervakken.json, src/tests/test_dynamic_api/test_filters.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views_api.py
Some of the schemas used for testing still have spaces in identifiers, which we haven't allowed for quite some time. This just bit me when I tried looking up fields by id on the parkeervakken schema.
I caught all of them if `git grep '".* .*":' src/tests` is to be trusted.
=> Remove spaces from field ids in test schemas

schemas/data/datasets/bag/bag.json
#399 removed spaces from fields in test schemas. This removes spaces from the copy of the BAG schema. We're not supposed to support those.
This should be a purely cosmetic change.
=> Remove spaces in BAG schema field ids

src/rest_framework_dso/filters/backends.py, src/tests/test_dynamic_api/test_filters.py
Invalid arguments to these filters now give error 400 instead of being silently ignored. Otherwise, the behavior is the same, no matter how strange it was. The tests ensure this and document some of the oddity.
=> AB#24677 Refactor and test geo filters, improve input validation

docker-compose.yml, src/dso_api/dynamic_api/serializers.py, src/dso_api/settings.py, src/tests/conftest.py, src/tests/test_dynamic_api/test_serializers.py
Fixes [AB#24665](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/24665)
The temporal _links factory was directly using the camel-cased values from the schema identifier field to add serializer fields by name. This did not lead to an error as long as the fields in the identifier of temporal schemas were equal to the camel-cased name used as the eventual database field name (i.e.: within ams schema context: they did not use shortnames and did not use uppercase letters) . These are now properly resolved by using the snakecased `DatasetFieldSchema.name` as the source of the field.
=> Properly resolve database source fields in temporal _links

src/dso_api/dynamic_api/serializers.py, src/rest_framework_dso/embedding.py, src/rest_framework_dso/fields.py, src/rest_framework_dso/serializers.py, src/rest_framework_dso/utils.py, src/tests/test_dynamic_api/test_filters.py, src/tests/test_rest_framework_dso/test_embedding.py, src/tests/test_rest_framework_dso/test_fields.py, src/tests/test_rest_framework_dso/test_serializers.py, src/tests/test_rest_framework_dso/test_views.py
This required a completely different parser (FieldsToDisplay) that can handle the various include/exclude patterns across different nesting levels. The final result still produces an allowlist of all fields that should be preserved, and which embeddings to preserve.
=> Allow ?_field=... to work across relations too.

src/tests/files/parkeervakken.json, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views_api.py, src/tests/test_dynamic_api/test_views_wfs.py
The auth tests assumed they would get 200 when filtering on a field that doesn't exist. That conflicts with the requirement of getting a 400 in this case. Add the field (`"volgnummer"`) and check for 404 instead, since we can't deliver the actual 400 yet.
There's a test that requires the same behavior for `"regimes.inWerkingOp"`, which was removed for [AB#24402](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/24402). This still needs updating.
=> AB#24678 Fix test_views_api.py

src/dso_api/dynamic_api/permissions.py, src/tests/conftest.py, src/tests/files/temporal_auth.json, src/tests/test_dynamic_api/test_temporal_actions.py
Some things to note:
1. The new code is in the wrong place. I'm still looking for the right place to put this. Ideally, we would validate the request much earlier in the process. That should fix the issue that invalid filters give 403 instead of 400.
2. `_parse_filter` is more general than necessary, in preparation for reimplementation of the filters.
=> Authorization on filters

schemas/data/datasets/bag/bag.json, src/requirements.in, src/requirements.txt, src/tests/files/afval.json, src/tests/files/bag.json, src/tests/files/bommen.json, src/tests/files/bommen@2.0.0.json, src/tests/files/brp.json, src/tests/files/download-url.json, src/tests/files/explosieven.json, src/tests/files/fietspaaltjes.json, src/tests/files/fietspaaltjes_no_display.json, src/tests/files/gebieden.json, src/tests/files/geometry_auth.json, src/tests/files/geometry_authdataset.json, src/tests/files/geometry_zoom.json, src/tests/files/haalcentraalbrk/schema.json, src/tests/files/indirect-self-ref.json, src/tests/files/meldingen.json, src/tests/files/parkeervakken.json, src/tests/files/temporal_auth.json, src/tests/files/unconventional_temporal.json, src/tests/files/vestiging.json, src/tests/files/woningbouwplannen.json, src/tests/utils.py
New version of `schema-tools` keeps track of active table versions. This is entirely transparant to all code that only uses `DatasetSchema`'s public API (methods and properties). Code that uses the underlying `dict` representation of `DatasetSchema`, however, will be affected. This PR has the necessary changes for those pieces of code.
=> Fix test schema's and code that uses DatasetSchema internal representation.

src/dso_api/dynamic_api/permissions.py, src/tests/test_dynamic_api/test_views_api.py, src/tests/test_rest_framework_dso/test_views.py
I forgot to whitelist this parameter. Of the tests, the one in `test_rest_framework_dso` doesn't actually trigger the bug, but I included it for completeness. The one in `test_dynamic_api` does, but it triggers a different bug, [AB#24678](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/24678).
=> AB#24404 Whitelist "page_size" in filter auth

src/dso_api/dynamic_api/routers.py
_build_db_viewsets was registering views without calling to_snake_case
on the dataset id. This caused beheerkaart_basis and beheerkaart_cbs grid to give a 500.
=> AB#24579 fix to_snake_case bug in router

src/dso_api/dynamic_api/serializers.py
I did this in a previous PR and thought it was covered by tests but that turned out to be a mistake. This requires a closer look at how through serialization works because now it is breaking the serialization of m2m relations. I will do this in a follow-up PR.
=> Do not include pk of non temporal targets when serializing through tables

src/tests/test_dynamic_api/test_views_api.py
Now covers JSON and tests page=2 as well. Serves as a regression test for eef66e13e7beef6c841ed09e7ab75bc656347d34.
=> Expand pagination test

docs/source/generic/rest.rst
This wasn't explained yet, and we got confused about it ourselves this morning.
=> Document pagination parameter "page"

src/dso_api/dynamic_api/permissions.py, src/tests/files/relationauth.json, src/tests/test_dynamic_api/test_filter_auth.py
Should work for all relation types, though the test only covers one-to-many within a dataset. The implementation isn't very efficient since it traverses the dataset collection for every single field. The caches in schema-tools should help a bit, though.
=> AB#24404 Fix filter auth on relations

src/dso_api/dynamic_api/middleware.py
This is a cosmetic change, in preparation for some validation middleware that I'm considering writing.
(It my remove some request latency, but don't expect miracles.)
There are no new tests because the existing ones cover this code: if I break it, existing tests fail.
=> Switch to modern (post-Django 1.10) middleware

src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/views/api.py, src/tests/test_dynamic_api/test_views_api.py
These would produce 500 instead of 400 due to a NameError.
It may seem overkill to introduce an exception class for this, but
* ValueError is too broad: it can be caused by a bug as well as a
validation check.
* Django's ValidationError isn't handled by DRF, so it would require
changes to the exception handler. I'm not willing to go there right
now.
* DRF's ValidationError may cause problems with non-DRF views such as
remotes. We want reusable validation/authorization code.
> * Tests
>
=> AB#24404 Handle syntax errors in filter parameters

src/rest_framework_dso/exceptions.py, src/rest_framework_dso/renderers.py, src/rest_framework_dso/serializers.py, src/rest_framework_dso/views.py, src/tests/test_rest_framework_dso/test_views.py, src/tests/utils.py
This directs users to the data supplier instead of having to ping us for support. Any exception that inherits from HumanReadableException is shown in full detail to end users on errors.
=> Improve error message when coordinate conversion fails during rendering

src/dso_api/dynamic_api/remote/clients.py
Key+cert is only used for BRK.
=> Clean up Haal Centraal clients

docs/source/datasets.py
WFS doesn't include the table-id as sub-path.
=> Fix WFS path in docs

src/dso_api/dynamic_api/remote/serializers.py, src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/temporal.py, src/dso_api/dynamic_api/utils.py, src/requirements.in, src/requirements.txt, src/rest_framework_dso/embedding.py, src/rest_framework_dso/fields.py, src/tests/conftest.py, src/tests/files/bag.json, src/tests/files/gebieden.json, src/tests/test_dynamic_api/test_views_api.py
* Fixes reverse M2M walking
* Fixes 500 error for some datasets (without `many=True`, m2m was walked as a 1n relationship)
* Apply temporal filtering to have the proper results for the current date only.
(vereist nieuwe schematools release: https://github.com/Amsterdam/schema-tools/pull/239)
=> Fix M2M relations in REST API

Jenkinsfile
Add a docker-compose project name with git hash to create a unique
network in the OWASP step. This prevents the step to break because
a lingering network from a previous run with a non-unique name exists.
> * Tests
>
=> Get fresh network names on Jenkins

src/tests/test_dynamic_api/test_filters.py
These tests were not actually passing an Accept-Crs header, since the "header" kwarg was being silently ignored by APIClient.get.
=> [AB#27822] Fix filter test CRS passing

src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/views/wfs.py
The `beheerkaartBasis` dataset id was converted into `beheerkaart_basis` when it was accessed via the `Dataset.name` attribute.  This change also reduces the need for an extra query to get the description.
=> Fix accessing /v1/wfs/beheerkaart/basis/ due to camel-case dataset name

dev-docs/source/environment.rst, src/dso_api/sentry.py, src/dso_api/settings.py, src/tests/test_sentry_filter.py
To be able to avoid sending events to sentry for specific datasets (urls).
=> Add a filter for Sentry

src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/views/index.py, src/dso_api/dynamic_api/views/mvt.py, src/dso_api/dynamic_api/views/wfs.py, src/dso_api/settings.py, src/templates/dso_api/dynamic_api/api.html
* Fixed Django `Dataset.name` usage (which can be `snake_case@version` identifier). Use `dataset.schema.id` instead.
* Instead of hiding the dataset, give an empty `environments` and `related_apis` section.
* Show responseText on browsable API for HTTP 500 error.
=> Fix the API index page, various API's were not listed due to resolve() issues.

src/dso_api/dynamic_api/views/mvt.py, src/tests/conftest.py, src/tests/files/geometry_auth.json, src/tests/test_dynamic_api/test_views_wfs.py
It used to pick the first geometry it could find, which can fail when there are multiple geo fields.
For [AB#30007](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/30007).
=> MVT should pick main geometry

src/tests/test_dynamic_api/test_views_api.py
TestAuth.test_mandatory_filters relied on our not checking the existence of a temporal field, which breaks the new filter implementation. Check an actual field instead.
=> [AB#24838] Fix mandatory filters test

src/tests/files/parkeervakken.json
This schema breaks the new filters, which look at the types in the schema instead of in the DB.
=> [AB#24838, AB#30003] Fix types in parkeervakken test schema

src/tests/test_rest_framework_dso/test_filters.py
Preliminary cleanup for [AB#24838](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/24838): this function is going to disappear and I'm porting all of these tests to use new filters (based on schemas instead of models). Removing this one first to make the final diff smaller.
=> Remove test for is_unfiltered (AB#24838)

dev-docs/source/auth.rst, dev-docs/source/howto/install.rst, src/dso_api/dynamic_api/management/commands/maketoken.py, src/dso_api/settings.py, src/jwks_test.json, src/tests/settings.py
The test key belongs in src/tests/settings.py, not the main settings.py. It also needs to be set when developing on the command line, or DSO-API fails to start with an AuthzConfigurationError. This is inconvenient, but much safer than the old setup.
=> Don't default to test JWKS (AB#38587)

src/rest_framework_dso/filters/lookups.py, src/tests/test_rest_framework_dso/test_filters.py
Needed for the filter rewrite ([AB#24838](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/24838)). Consistent with #459.
This function will be moved elsewhere in a later PR.
=> Factor out SQL wildcard translation as a freestanding function

src/dso_api/dynamic_api/permissions.py, src/tests/test_dynamic_api/test_views_api.py
The main part of this PR is a partial revert of 8609348380047381e14c14c31ad498814ca7eb54. I removed too much of the `mandatoryFilters` handling, breaking a test.
The issue here is that when a filter is mandatory, it must also be allowed, regardless of whether the field being used to filter is accessible. This may be something that we need to rethink, but for now, this test needs to pass.
=> Restore mandatoryFilters handling, fix test

src/dso_api/dynamic_api/permissions.py, src/tests/files/relationauthcomposite.json, src/tests/test_dynamic_api/test_request_validation.py
Relations with composite keys would error out with 500 because the auth/validation check assumed `DatasetFieldSchema.related_field_ids` would return a single value. That is obviously not true for such fields.
=> Fix auth check on composite relation fields

docs/source/generic/rest/filtering.rst, src/dso_api/dynamic_api/permissions.py, src/tests/test_dynamic_api/test_request_validation.py
The docs said the filter name is the name of the relation field + the name of the id to which the relation refers. That's not true, it's simply always field name + "Id".
=> Fix filtering on relations, and fix the docs too

src/dso_api/dynamic_api/permissions.py, src/tests/files/relationauth.json, src/tests/files/relationauthcomposite.json, src/tests/test_dynamic_api/test_request_validation.py
This should make afvalwijzer work again, though with the old +"Id" syntax.
Tests have been restored, expanded and commented upon. They have also been updated to no longer use an "auth" field on an identifier, since the schema validation in schema-tools no longer allows that (identifiers show up in URLs anyway, so hiding them otherwise makes little sense).
=> Fix relation filter validation, again (AB#40932)

docs/Dockerfile, src/Dockerfile
Update the base images to the bullseye release to fix the CVE's below:
- Debian Security Update for expat (DSA 5085-2)
- Debian Security Update for Open Secure Sockets Layer (OpenSSL) (DSA 5103-1)
- GNU Bash Privilege Escalation Vulnerability for Debian
- Debian Security Update for tiff (DSA 5108-1)
- Debian Security Update for zlib (DSA 5111-1)
=> Update base images to bullseye release

src/dso_api/dynamic_api/serializers.py, src/rest_framework_dso/fields.py, src/tests/test_rest_framework_dso/test_fields.py
Explicit is better than implicit: this way, the method has a name indicating what it does, and we no longer need a reminder at the call site that we overloaded `__bool__` with a meaning that is not obvious. Also, PyCharm can find the method's call site, which it can't for `__bool__` without extensive type annotations.
=> Rename FieldsToDisplay.__bool__ to FieldsToDisplay.reduced

src/dso_api/dynamic_api/filters/parser.py, src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/remote/clients.py, src/dso_api/dynamic_api/temporal.py, src/dso_api/dynamic_api/views/api.py, src/requirements.in, src/requirements.txt, src/tests/files/movies.json, src/tests/test_dynamic_api/test_filters.py, src/tests/test_dynamic_api/test_request_validation.py, src/tests/test_dynamic_api/test_views_api.py
This replaces some functions to use a FilterPathPart that will handle
both a DatasetFieldSchema and AdditionalRelationSchema object. These
objects differ tremendously in their API and usage.
The early requests permissions check are removed, as the filters already do this.
This also avoids double-parsing the request, and double bookkeeping
when new features are added to the filter engine.
=> Implemented reverse-relation support in the new filter engine

src/dso_api/dynamic_api/serializers.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views_api.py
While it may "look" nicer to avoid null values, this makes browsable discovery of relations much harder, and we found this raises more questions on what is possible.
---
To discuss: we talked about this option because of received `feedback`, but I can't find the ticket number for this anymore..
=> Show all relation values in the _links, even if they are null (reverts AB#7538)

src/dso_api/dynamic_api/remote/clients.py, src/dso_api/settings.py, src/tests/test_dynamic_api/remote/test_views.py
We want "Missing API Key" from the remote, not "Invalid API Key",
when we can't send the key.
=> Get better diagnostics for missing API keys in remotes

src/requirements.in, src/requirements.txt
This release fixes CVE-2022-34265.
=> Bump Django to 3.2.14

src/dso_api/static/dso_api/dynamic_api/css/browsable_api.css, src/dso_api/static/dso_api/dynamic_api/js/browsable_api.js
browsable api can now match Open API paths with parameters like
'/v1/dataset/table/{id}'
=> Bugfix browsable API works with all endpoints

src/.jenkins/owasp_vulnerability_scan/owasp_scan.py
Scanning BAG stalls at 90%. Maybe the smaller dataset fietspaaltjes is easier to scan.
=> Try OWASP on fietspaaltjes and log the URLs

src/.jenkins/owasp_vulnerability_scan/docker-compose.yml
The new version gets stuck on 90% progress in the scan without an
indication of what is going wrong. We should fix this more thoroughly
and improve the logging, but for now we'll stick to a version that has
worked in the past.
This reverts commit 9bfc9d58c48a6024e4a49c98506bef34b40a16b4.
=> Revert "Upgrade OWASP ZAP (#545)"

src/dso_api/dynamic_api/models.py, src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/serializers.py, src/dso_api/dynamic_api/utils.py, src/requirements.in, src/requirements.txt, src/rest_framework_dso/embedding.py, src/rest_framework_dso/serializers.py, src/rest_framework_dso/utils.py, src/tests/test_dynamic_api/test_utils.py
This reorganizes the serializer `to_representation()` logic that optimizes the incoming querysets, and applies `.only()` on them. The prefetch-related logic is also updated.
Some existing code had to be reorganized/moved for reuse, which is stored in separate commits.
=> Limit the requested database fields using .only()

src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/serializers/__init__.py, src/dso_api/dynamic_api/serializers/base.py, src/dso_api/dynamic_api/serializers/factories.py, src/dso_api/dynamic_api/serializers/fields.py, src/dso_api/dynamic_api/utils.py, src/tests/test_dynamic_api/test_serializers.py
Literal code split, no changes except for documentation improvements.
=> Split dynamic_api/serializers.py into factory and runtime serializer part

src/dso_api/dynamic_api/serializers/base.py, src/dso_api/dynamic_api/serializers/factories.py, src/dso_api/dynamic_api/utils.py, src/rest_framework_dso/serializers.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views_api.py
This reorganizes the serializers, so permission checks can be applied to the serializer `_links` elements,
Commit 1 reorganizes the `LinksSerializer` class hierarchy so it no longer has to disable functionality from the base class.
Commit 2 inserts the checks and deals with the side effects from that.
Lastly, when a link item would not return any fields, it will omit the entry completely.
=> Hide fields in _links when there is no access for it (e.g. display field)

src/dso_api/dynamic_api/filters/__init__.py, src/dso_api/dynamic_api/filters/parser.py, src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/remote/clients.py
And use it in the remote filters, so we no longer have two implementations.
=> Port permissions.parse_filter to new filter parser

src/dso_api/dynamic_api/serializers/base.py
The _links field was missing in calls such as: https://api.data.amsterdam.nl/v1/bag/openbareruimtes/?_fields=naam&_pageSize=&_sort=naam&ligtInWoonplaats.identificatie=3594
This happens due to the `?_fields=..` stripping the `_links` block as well. Previously, `DSOSerializer.fields_always_included` prevented this, but `FieldAccessMixin` redefined this variable with a new default as of 1e81980c9c331a77ca633c0565de471ed5c83624.
=> Hotfix to repair external GetAlleStratenAmsterdam call

src/rest_framework_dso/crs.py, src/rest_framework_dso/views.py
ALL_CRS was never used. Instead, its value was repeated in views.py.
ETRS89 and WEB_MERCATOR no longer need to be exported.
=> CRS cleanup

src/rest_framework_dso/renderers.py
HALJSONRenderer._render_json was looking at the wrong value to determine whether to call itself recursively: it only did so for
`isinstance(data, str)`, after first checking that `isinstance(data, dict)`.
With this patch, the optimization actually works and shows a small improvement on the data for the first 10000 `openbareverlichting` items. Before:
```
>>> r = renderers.HALJSONRenderer()
>>> %timeit all(r.render(data))
9.32 ms ± 542 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
After:
```
9.12 ms ± 10.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
=> Fix JSON rendering optimization

src/requirements.in, src/requirements.txt
Bump Django to version 3.2.15: https://docs.djangoproject.com/en/dev/releases/3.2.15/
=> Bump Django to v3.2.15

src/dso_api/dynamic_api/filters/openapi.py
Enums uit amsterdam schema werden niet meegenomen in de openapi spec. Door deze pr wel. Zo komen ze ook in de suggesties van de browsable api
=> Add field enums to openapi parameters

src/dso_api/dynamic_api/serializers/fields.py
This only happens when databases and schema don't match, but raising a 500 is a bit too much for this.
=> Make the code more robust for temporal relations that are integers

dev-docs/source/auth.rst
Just don't mention the expiry. Power users will run --help.
=> Update docs for maketoken

src/dso_api/dynamic_api/filters/parser.py
Should fix
https://api.data.amsterdam.nl/v1/loopfietsnetwerk/edges/?startNode.nodeId=1
and friends.
=> Fix non-loose 1-N relation filtering

.gitignore, src/dso_api/settings.py
When running the dso-api as a task, we use the em4w admin group through the AKS mid with time-limited token-based authentication
fixes [AB#55947](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/55947)
=> Use em4w admin token when running as task

src/tests/conftest.py, src/tests/test_dynamic_api/test_filters.py
Inspired by a case reported on Slack where this doesn't work. Won't fix the issue, but makes it easier to spot regressions.
=> Test isnull filter on a relation field

src/dso_api/dynamic_api/filters/lookups.py, src/dso_api/dynamic_api/filters/values.py, src/dso_api/dynamic_api/management/commands/maketoken.py, src/dso_api/dynamic_api/openapi.py, src/dso_api/middleware.py, src/dso_api/settings.py, src/requirements.in, src/requirements.txt, src/requirements_dev.txt, src/rest_framework_dso/openapi.py, src/tests/conftest.py
Bump all requirements for  security, future maintenance and to make room for future Django upgrades.
Django is kept at 3.2 for LTS support, but running this code on Django 4.0 works.
For Django 4.1 tests to pass, the ChunkedQuerysetIterator needs to be removed because Django 4.1 does the same internally.
=> Bump requirements for security, future maintenance and space for Django 4

docs/Dockerfile
Generating the docs is one of the slower parts of our builds.
With this patch, on a 16-core laptop, I see
docker build --build-arg BUILD_NUMBER=x .
(w/ fresh x) speed up by about a factor 4. The sequential part is writing the generated files out to disk.
=> Run sphinx-build with parallel workers

src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/serializers/factories.py
This guards against changes in schematools that could break models in subtle ways.
=> Improve Django startup, show model validation errors on broken models

docs/source/datasets.py, src/dso_api/dynamic_api/filters/openapi.py, src/dso_api/dynamic_api/filters/parser.py, src/dso_api/dynamic_api/management/commands/dump_serializers.py, src/dso_api/dynamic_api/management/commands/implement_constraint.py, src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/remote/serializers.py, src/dso_api/dynamic_api/remote/views.py, src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/serializers/factories.py, src/dso_api/dynamic_api/serializers/fields.py, src/dso_api/dynamic_api/temporal.py, src/dso_api/dynamic_api/utils.py, src/dso_api/dynamic_api/views/api.py, src/dso_api/dynamic_api/views/mvt.py, src/requirements.in, src/requirements.txt, src/rest_framework_dso/views.py, src/tests/files/fietspaaltjes.json, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views_api.py, src/tests/utils.py
This fixes the shortnames appearing in the API.
The cause of this bug happened deep inside schematools, where the `field.name` would return the database `shortname`. Thus, model fields, and even API serializer fields received that shortname. This PR brings DSO-API in line with the changes in schematools.
=> Update DSO-API with new schematools release changes

docs/requirements.txt, docs/source/_templates/datasets/dataset.rst.j2, docs/source/_templates/wfs-datasets/dataset.rst.j2, docs/source/datasets.py, src/dso_api/dynamic_api/serializers/factories.py, src/rest_framework_dso/embedding.py, src/rest_framework_dso/openapi.py, src/tests/test_rest_framework_dso/models.py, src/tests/test_rest_framework_dso/test_serializers.py, src/tests/test_rest_framework_dso/test_views.py
Also mark old deprecated names that still appear in the OpenAPI view (no shortnames are shown there either)
=> Update API documentation, hide shortname syntax in API view

docs/source/_templates/datasets/dataset.rst.j2, src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/urls.py, src/dso_api/dynamic_api/views/__init__.py, src/dso_api/dynamic_api/views/doc.py, src/dso_api/dynamic_api/views/mvt.py, src/templates/dso_api/dynamic_api/docs/dataset.html, src/templates/dso_api/dynamic_api/docs/overview.html, src/templates/dso_api/dynamic_api/mvt_single.html
This adds an endpoint /v1/docs/datasets/{dataset_id}.html that displays automatically generated HTML documentation for a dataset. The contents match those of the Sphinx documentation, which these docs must ultimately replace. There is also an overview of datasets at /v1/docs/.
The HTML isn't styled yet, but the functionality is there. For now, this will not display on api.data.amsterdam.nl/v1/docs/, which uses proxy rules to display docs from a separate Docker image instead.
For [AB#56614](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/56614).
=> Generate docs on the fly

src/dso_api/dynamic_api/views/doc.py, src/templates/dso_api/dynamic_api/docs/dataset.html, src/templates/dso_api/dynamic_api/docs/overview.html, src/tests/test_dynamic_api/test_doc.py
Includes a unit test. For [AB#61560](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/61560).
Also adds compression, which should be safe here because the response bodies are practically static.
=> Dataset docs: generate URLs using the router

README.md
This includes some instructions for Vim that don't actually seem to work. GitHub is displaying them, which looks rather unprofessional.
=> Remove some cruft from the README

docs/source/datasets.py
With this change, `bag_azure` and `brk2` no longer appear in `source/datasets`, `source/wfs-datasets` or the `index.rst` files in those directories.
=> Don't build docs for datasets marked niet_beschikbaar

src/tests/conftest.py, src/tests/test_dynamic_api/test_filters.py, src/tests/test_dynamic_api/test_views_api.py
For [AB#60099](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/60099). Doesn't solve the issue, but should narrow it down.
=> Expand tests for relation[isnull] filters

src/dso_api/dynamic_api/filters/parser.py, src/tests/conftest.py, src/tests/files/huishoudelijkafval/cluster/v2.0.0.json, src/tests/files/huishoudelijkafval/dataset.json, src/tests/test_dynamic_api/test_filters.py
This would previously check whether an object is related to another object with a null identifier, which would always fail. It now checks whether the relation is present at all.
Includes a severely trimmed version of the huishoudelijkafval dataset from amsterdam-schema, since no other present test set would exhibit the buggy behavior.
Fixes [AB#60099](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/60099).
=> Fix filter relation.ident[isnull]=true

src/dso_api/dynamic_api/views/doc.py, src/templates/dso_api/dynamic_api/docs/dataset.html, src/templates/dso_api/dynamic_api/docs/dataset_wfs.html, src/tests/test_dynamic_api/test_doc.py
Convert ReST quotes to ``<code>`` in HTML docs, restore missing export links, code cosmetics.
For [AB#61559](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/61559).
=> Fixup HTML docs

src/dso_api/dynamic_api/urls.py, src/dso_api/dynamic_api/views/doc.py, src/templates/dso_api/dynamic_api/docs/gis/manual.md, src/templates/dso_api/dynamic_api/docs/gis/qgis.md, src/templates/dso_api/dynamic_api/docs/gis/wfs_technical.md
Again converted with pandoc -t gfm, but with the images manually fixed up afterward.
=> Port GIS docs to Markdown as well

src/dso_api/dynamic_api/views/doc.py
This is required to render triple-backtick blocks the GFM way.
=> Fix code display from Markdown

src/requirements.in
This pins our jwcrypto version to >= 1.4.2.
=> Bump requirement authorization_django

src/dso_api/dynamic_api/serializers/fields.py
Add the view name and the field. Not the value, as that may contain sensitive information.
=> More useful error message from TemporalHyperlinkedRelatedField

src/dso_api/static/dso_api/dynamic_api/css/browsable_api.css
Because the license ends. Now use "Amsterdam Sans".
This font is included in the Amsterdam static css that is loaded by DSO browsable api.
=> AB-62685 Remove use of Avenir font

src/dso_api/dynamic_api/filters/openapi.py, src/dso_api/dynamic_api/serializers/base.py, src/dso_api/dynamic_api/serializers/factories.py, src/dso_api/dynamic_api/serializers/fields.py, src/requirements.in, src/requirements.txt, src/rest_framework_dso/serializers.py, src/rest_framework_dso/utils.py, src/tests/conftest.py, src/tests/files/datasets/aardgasverbruik.json, src/tests/test_dynamic_api/test_serializers.py
This addresses the needs for the dataset 'aardgasverbruik', that has a primary key that is also a relationship.
=> Add support for primary keys that have a relation

src/requirements.in, src/requirements.txt, src/rest_framework_dso/views.py, src/tests/files/datasets/afval.json, src/tests/test_dynamic_api/test_views_api.py
Uses the new version of gisserver, which no longer raises `SyntaxError`. Only check for its `ExternalValueError` type, so we don't send error 406 for `ValueErrors` caused by bugs.
Fixes [AB#67466](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/67466).
=> Fix invalid CRS handling

.pre-commit-config.yaml, src/dso_api/dynamic_api/views/doc.py
`/v1/docs` is broken because of one dataset. I can't reproduce the error locally. For now, log the error so we can serve the rest of the list.
=> Docs: log and ignore broken datasets

src/requirements_dev.txt
It's also in requirements.in, and the versions were different.
=> Remove pip-tools from requirements_dev.txt

src/dso_api/settings.py
The previous patch fixed a local install in debug mode, but not the server deployment, which still fails to send Content-Type headers.
=> Remove X-Content-Type-Options: nosniff

dev-docs/source/howto/install.rst, src/Dockerfile, src/dso_api/settings.py
Whitenoise needs to install the static files somewhere writable, because it generates gzipped versions of them dynamically.
With this patch, DSO-API will refuse to start when `DSO_STATIC_DIR` is not set. That seems a better option to me than letting it pick some implicit default location.
=> Configure static files dir with env var DSO_STATIC_DIR

src/dso_api/dynamic_api/openapi.py
Documentation link was pointing to production independent of environment. Now we use the DATAPUNT_API_URL envronment setting, so the OPENAPI spec in acceptance points to acceptance docs
> * Tests
>
=> Fix documentation link in OpenAPI spec

src/dso_api/dynamic_api/openapi.py
The spec for BAG takes 5.7s to construct on my laptop, and is 1.81 MB large. Using gzip_page compresses it down to 86 kB, or a factor 21 smaller. Caching it means it gets loaded instantly the second time.
=> Compress and cache OpenAPI specs

src/dso_api/static/dso_api/dynamic_api/js/browsable_api.js, src/rest_framework_dso/renderers.py, src/templates/dso_api/dynamic_api/api.html
Authorize button was using the oauth_uri from OpenAPI spec. So it was not available on all pages.
Now it is injected into the view, so the authorization button appears on all pages.
> * Tests
>
=> Display authorize button on every page

src/dso_api/dynamic_api/openapi.py
OpenAPI pages inconsistently deliver JSON or HTML
pages in browser. Revert for now, look at this monday
> * Tests
>
=> Revert OpenAPI caching and compression

src/dso_api/dynamic_api/filters/parser.py, src/dso_api/dynamic_api/temporal.py
An empty `django.db.models.Q` object is a no-op and is False in a boolean context. Use that to our advantage: we don't need to build up lists of `Q`'s with special handling for empty lists. Only `QueryFilterEngine.filter_queryset` needs to check whether it needs to do any work.
I also removed `LOOKUP_MERGE_OPERATORS`, which was just a complicated way of checking for `not`.
=> Simplify filter implementation

src/dso_api/static/dso_api/dynamic_api/css/browsable_api.css, src/dso_api/static/dso_api/dynamic_api/js/browsable_api.js
Users like to extract the token for debugging and other things. THis adds a button next to the token header field, to copy the token to the clipboard.
> * Tests
>
=> Add button to copy token to clipboard

src/dso_api/dynamic_api/serializers/factories.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_temporal_actions.py, src/tests/test_dynamic_api/test_views_api.py
Instead of
"id": "foo.1"
we now render
"identificatie": "foo", "volgnummer": 1
(assuming conventional field names).
Fixes [AB#7597](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/7597). Also fixes a bug where a field inside an object-typed field was removed because its name matched with one of the identifier fields that were previously removed.
=> Render temporal fields instead of synthetic identifier

src/dso_api/dynamic_api/views/doc.py, src/templates/dso_api/dynamic_api/docs/dataset.html, src/tests/files/datasets/fietspaaltjes.json, src/tests/files/publishers/NOBODY.json, src/tests/test_dynamic_api/test_doc.py
Locally, publishers would display as
{'name': 'Datateam Stedelijke Ontwikkeling en Beheer', 'id': 'SOEB', 'shortname': 'soeb', 'tags': {'team': 'stedelijke ontwikkeling en beheer', 'costcenter': '738000002.4810.13519'}, 'type': 'publisher'}
while on PROD, they would display as
{'$ref': 'publishers/SOEB'}
Try to expand the publishers. Needs a workaround for the unit tests, where the loader on a dataset schema is apparently reset to an instance of the base class SchemaLoader. I've no idea what's going on there.
=> Fix publishers display in docs

src/rest_framework_dso/paginator.py
This method duplicates the functionality of `ObservableIterator.add_observer`. It isn't called anywhere.
=> Remove unused method ObservableQuerySet.add_observer

src/rest_framework_dso/renderers.py
Bytes concatenation `x+y` is about 10x faster than `b"%b%b" % (x,y)`.
`sep + orjson.dumps({key: value})` is a bit faster than formatting. We now need to construct a `dict`, but we no longer need to construct a `tuple`, so the memory allocation costs are similar.
`HALJSONRenderer.render_json` is now some 6% faster on my (ad hoc) microbenchmark.
=> More micro-optimizing on JSON rendering

src/dso_api/dynamic_api/openapi.py, src/dso_api/dynamic_api/views/doc.py, src/dso_api/settings.py
This reduces bandwidth for ordinary JSON responses by a factor 4-7, GeoJSON by up to a factor 10, and even MVT responses are compressible.
HTTP compression exposes us to the [BREACH](https://www.breachattack.com/) attack, which reconstructs secrets in the response body by looking at how its length changes from echoing parts of the requests. In practice, that means CSRF tokens can be leaked. But we don't use CSRF tokens for anything. We pass tokens in the request header, which doesn't get compressed.
=> gzip all the responses

src/dso_api/settings.py, src/requirements.in, src/requirements_dev.in, src/tests/conftest.py
For now, the API Key has been set to be optional.
However, if provided, it will be validated.
pip-tools needed to be upgraded to get it running again. Django check gave a warning about the Middleware not being in the correct order in the settings.MIDDLEWARE, so it had been moved.
=> Add API Key Middleware

src/templates/dso_api/dynamic_api/api.html
Because the azure production environment is not yet ready, we commented out the link to the apikey server form.
=> Temporary removal of link to api key server.

dev-docs/source/howto/install.rst, src/dso_api/settings.py
It can be annoying that the api key middelware keeps trying to get the signing keys when developing the dso locally.
So, now an environment variable `APIKEY_ENABLED` can be used to avoid the activation of the api key middleware. If the value of `APIKEY_ENABLED` is `false`, the middleware is not activated.
=> Make useage of api keys configurable.

src/dso_api/settings.py
Because we want to proxy from HAProxy to Azure, we need to use this header.
=> Enable use of X-Forwarded-Host

src/templates/dso_api/dynamic_api/api.html
Now that the api key server is running in PRD
we can re-add the link to the form where a key can be requested.
=> Re-add the link to the api key form.

src/dso_api/dynamic_api/views/api.py, src/tests/test_dynamic_api/test_views_api.py
When a single resource was being accessed through the api, the full records was being collected from the datbase. However, in the PostgreSQL Azure situation, this fails, because the scope of the user is being used during database access.
Now the set of fields for this particular resource is being checked against the scopes of the requesting user. If needed, the Django ORM query is limited to the allowed fields only.
This scenario was already being unittested. However, the test framework has only one test database setup. It would be very time consuming to set up an extra postgres instance with the correct set of roles. So this aspect is not being unittested atm.
=> AB#97545 Fix for db permission error on single record access.

src/Makefile, src/dso_api/dynamic_api/models.py, src/dso_api/dynamic_api/permissions.py, src/dso_api/dynamic_api/serializers/base.py, src/dso_api/dynamic_api/utils.py, src/dso_api/dynamic_api/views/api.py, src/dso_api/settings.py, src/rest_framework_dso/fields.py, src/tests/conftest.py, src/tests/files/datasets/monumenten.json, src/tests/settings.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/test_views_api.py, src/tests/utils.py
The Django ORM has been designed around the idea that a single database user with wide permissions is accessing the database. Authorization-based filtering is done at the python level, e.g. in DRF serializers.
However, our PostgreSQL database has been protected at the row-level with fine-grained permissions and the user accessing the database is not a generic database user, but the user accessing the API (based on the JWT auth token).
This leads to problems, especially when following relations. The Django ORM tries to fetch all rows (SELECT * FROM) and a permission exception will be raised by the database driver.
At several places extra scope-checks need to be applied to force the ORM to only fetch the rows that are allowed.
=> AB#101824 fix partially protected relations

src/dso_api/dynamic_api/views/doc.py
To generate the viewnames for the documentation, the db_name_variant function was used. However, that takes shortnames into account. The Django viewset ids names are using the full names of the schema-tables, so there is a mismatch leading to a 500 error for datasettables with a shortname.
=> AB#104026 Fix viewset name for docs

src/dso_api/settings.py
For easier switching without re-deploy.
=> Make APIKEY_MANDATORY configurable from env var.

src/dso_api/dynamic_api/permissions.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/utils.py
It should be possible for a request to fetch unprotected fields (using the `_fields` query parameter).
=> AB#107499 Fix issue with expand query with only open fields

src/requirements.in, src/requirements.txt, src/requirements_dev.txt
For the `DatasetTable.id_fields` needed for geosearch.
=> Bump schematools to 5.26.0

src/dso_api/settings.py
This was an old setting, because bag was being geosearched using the old bag/v11 until recently. But now, we want geosearch to use the ref db for Bag.
=> Remove setting that causes disabling of geosearch for datasets.

src/dso_api/dynamic_api/management/commands/dump_serializers.py, src/dso_api/dynamic_api/openapi.py, src/dso_api/dynamic_api/remote/views.py, src/requirements.in, src/requirements.txt, src/requirements_dev.txt
This improves the performance of has_field_access() checks and direct "auth" field access.
As part of this improvement, the call signature of has_all_scopes() was changed, which affected the old Haalcentraal BRK API proxy code.
=> Upgrade to amsterdam-schema-tools 6.0 for better performance

.github/dependabot.yml
Have Dependabot group minor (and patch) pip version updates into one PR. 
This will hopefully make the number of PRs more managable without grouping PRs that may cause issues. 
PRs for updates that resolve security issues will still be created separately.
=> Group minor Dependabot pip updates into one pr

src/dso_api/dynamic_api/views/api.py, src/dso_api/settings.py, src/rest_framework_dso/embedding.py, src/rest_framework_dso/iterators.py, src/rest_framework_dso/paginator.py, src/tests/test_dynamic_api/views/test_api_auth.py, src/tests/test_rest_framework_dso/test_iterators.py, src/tests/test_rest_framework_dso/test_views.py
* Report when database roles have no access (no longer gives a 500)
* Fix 500 error HTML response messing up JSON syntax highlight.
* Make error handling easier, no longer jump through hoops to have a 404 for invalid page numbers.
* Remove server-side cursors as that breaks with PgBouncer.
=> Fix database error message handling

src/dso_api/static/dso_api/dynamic_api/js/browsable_api.js
Button was meant to allow quick bebugging in curl. But it is easily abused for loading data into other applications. This update removes the button.
=> Remove copy token button form browsable api

src/dso_api/dynamic_api/views/mvt.py, src/tests/test_dynamic_api/views/test_mvt.py
This ensures that the fields on the feature are camelCased. 
- Altered the existing test so that the expected response conforms to the schema. 
- Annotated the queryset with the camelCased field names referring to their db names.
- Added the correct names to the tile_fields. 
- Refactored to dedupe logic.
=> MVT correct field names

src/dso_api/dynamic_api/filters/lookups.py, src/dso_api/dynamic_api/filters/parser.py, src/tests/test_dynamic_api/test_filters.py
=> implemented case insensitive search

src/dso_api/static/dso_api/dynamic_api/js/browsable_api.js
User input was not properly sanitized before writing to DOM.
This should fix an issue brought up by github code-scanning.
=> Fix xss vulnerability in browsable api

src/dso_api/dynamic_api/views/mvt.py, src/tests/test_dynamic_api/views/test_mvt.py
Hierdoor zijn de identifiers aanwezig ongeacht het zoomniveau.
=> Altijd identifiers toevoegen in MVT data

src/dso_api/dynamic_api/views/wfs.py, src/tests/test_dynamic_api/views/test_wfs.py
Velden misten als je geen auth had, terwijl op de index pagina alleen de metadata van de velden - type, description - wordt getoond. Deze data is ook al beschikbaar in het schema en in de docs. 
Zie discussie: https://datalab-amsterdam.slack.com/archives/CJW3HEAKH/p1742372795066099
Ticket: https://datalab-amsterdam.slack.com/lists/T067TBC4S/F07B2E8F21X?record_id=Rec08HAEWRLJK
NB voor het opvragen van records is natuurlijk nog wel steeds authorisatie nodig.
=> Show all fields on wfs index page

dev-docs/source/api/dso_api.dynamic_api.views.rst, src/dso_api/dynamic_api/filters/values.py, src/dso_api/dynamic_api/routers.py, src/dso_api/dynamic_api/views/__init__.py, src/dso_api/dynamic_api/views/mvt.py, src/templates/dso_api/dynamic_api/docs/gis/qgis.md, src/tests/test_dynamic_api/views/test_mvt.py
Dit voegt een tilejson.json route toe voor alle datasets. Daarin zijn vervolgens de verschillende tile layers te vinden (1 voor elke tabel die een geoveld heeft). 
Geeft 404 voor datasets met alleen tabellen zonder geoveld. 
NB: Ik heb overigens nog geen manier gevonden om dit zo in QGis in te laden dat ie alle lagen toevoegt. Had een plugin gevonden die met TileJSON overweg kan, maar die pakt alleen de eerste. In de meeste voorbeelden van tilejsons online zie ik trouwens ook dat het een lijst is van verschillende endpoints die dezelfde data geven, ipv daadwerkelijk verschillende lagen. Wellicht is het de intentie dat dit per tabel wordt gedaan ipv per dataset?
=> MVT tilejson

src/dso_api/dynamic_api/views/mvt.py, src/dso_api/dynamic_api/views/mvt_base.py, src/tests/test_dynamic_api/views/test_mvt.py
I'm not sure if we should merge this, but if MVT turns out to still take too much memory, it's here as an option.
=> Rewrite MVT to take constant instead of linear memory

src/dso_api/wsgi.py
This way endusers will not experience a slow response when a new pod starts or a worker is restarted.
Based on http://uwsgi-docs.readthedocs.org/en/latest/articles/TheArtOfGracefulReloading.html#dealing-with-ultra-lazy-apps-like-django
Gets rid of slow responses during redeploys and scaling operations in kubernetes.
=> Warmup Django before exposing uWSGI worker

src/dso_api/dynamic_api/views/mvt.py, src/requirements.in, src/requirements.txt, src/requirements_dev.txt, src/tests/files/datasets/gebieden.json, src/tests/test_dynamic_api/views/test_mvt.py
Dit zorgt ervoor dat mvt details alleen worden getoond als de zoom zich tussen min en max bevindt (beiden inclusief).
=> Use table zoom levels

src/rest_framework_dso/crs.py, src/rest_framework_dso/renderers.py, src/tests/conftest.py, src/tests/test_dynamic_api/test_serializers.py, src/tests/test_dynamic_api/views/test_api.py, src/tests/test_dynamic_api/views/test_api_filters.py, src/tests/test_dynamic_api/views/test_api_formats.py, src/tests/test_dynamic_api/views/test_wfs.py, src/tests/test_rest_framework_dso/test_views.py
Even when asking "Accept-Crs: EPSG:4326", the ordering was previously x/y.
Since django-gisserver 2.0 we follow the axis ordering of the format, making it y/x in the REST API.
In GeoJSON this isn't changed, as the standard mandates that all coordinates are in x/y format.
=> Confirm coordinate for REST API and GeoJSON

src/dso_api/settings.py, src/requirements.in, src/requirements.txt, src/requirements_dev.txt, src/tests/conftest.py, src/tests/test_user_context.py
So extra permissions for mandatoryFilterSets can be applied
> * Tests
>
=> Set db role settings to filtered variants

src/tests/conftest.py, src/tests/files/datasets/beheerkaart/basis/bgt/v1.json, src/tests/files/datasets/beheerkaart/basis/dataset.json, src/tests/test_dynamic_api/views/test_api.py
This broke in prod after versioned datasets were released. Schematools 8.1.1 contains the fix on the schema-tools side and was already applied to dso-api. This is just a couple tests to ensure it won't break.
=> Unittests for nested datasets
