src/dso_api/datasets/management/commands/import_schemas.py

Fixed import in management command

Fixing import.

---

src/dso_api/dynamic_api/urls.py
src/dso_api/dynamic_api/views.py
src/dso_api/settings.py
src/requirements.in
src/requirements.txt

To expose the view, extend WFSView, and define the Feature Type for each model
Features:
- Extensible view/operations
- Using geodjango queries for filtering.
- Using Django template engine for rendering XML
- Unit tests currently validate response format only.
- Using dynamic WFSMethod parameter parsing and introspection.
TODO: remaining WFS pagination and filtering parameters

Implemented basic WFS 2.0 compatible mapserver component (spike)

---

src/dso_api/lib/schematools/models.py
src/tests/files/afval.json
src/tests/test_dynamic_api/test_models.py
src/tests/test_dynamic_api/test_serializers.py

Restore the setting of the correct srid from amsterdam schema.
Added index to geo fields.
Added and fixed tests.

Added geo related info to models.

---

src/dso_api/lib/schematools/models.py

Type lookups obv url waren afhankelijk van de volledige url inclusief versie. Leidt al snel tot key errors.

Make type lookup independent of amsterdam schema version.

---

src/dso_api/lib/schematools/models.py

- Slugify dataset.id, it can contain spaces
- Add "time" as possible format for json schema "format"

Small fixes to modelgeneration.

---

src/dso_api/dynamic_api/filterset.py
src/dso_api/dynamic_api/permissions.py
src/dso_api/lib/schematools/models.py
src/rest_framework_dso/filters.py
src/setup.cfg
src/setup.py

using arrays and fix for permissions
Some changes  are copied form branches from Nick

Required changes for using this as module,

---

src/dso_api/dynamic_api/filterset.py
src/dso_api/dynamic_api/routers.py
src/dso_api/dynamic_api/serializers.py
src/dso_api/dynamic_api/utils.py
src/dso_api/dynamic_api/views.py
src/requirements.in
src/requirements.txt
src/rest_framework_dso/filters.py
src/rest_framework_dso/serializers.py
src/tests/conftest.py
src/tests/files/parkeervakken.json
src/tests/test_dynamic_api/test_serializers.py
src/tests/test_rest_framework_dso/test_serializers.py

Allow nested APIs to be displayed via DSO API

Nested tables in API.

---

src/dso_api/dynamic_api/remote/__init__.py
src/dso_api/dynamic_api/remote/serializers.py
src/dso_api/dynamic_api/remote/views.py
src/dso_api/dynamic_api/routers.py
src/dso_api/dynamic_api/serializers.py
src/dso_api/lib/exceptions.py
src/requirements.in
src/requirements.txt
src/rest_framework_dso/serializers.py
src/rest_framework_dso/views.py
src/tests/conftest.py
src/tests/files/brp.json
src/tests/test_dynamic_api/remote/test_views.py
src/tests/test_rest_framework_dso/test_serializers.py
src/tests/test_rest_framework_dso/test_views.py

* Splits DSOSerializer / DSOModelSerializer
* Reads `Dataset.endpoint_url` / `Dataset.enable_db` (schematools 0.6)

DS-265 implemented remote service proxy support

---

README.md
docker-compose.yml
src/.jenkins/test/docker-compose.yml
src/dso_api/dynamic_api/permissions.py
src/dso_api/dynamic_api/views.py
src/dso_api/settings.py
src/tests/conftest.py
src/tests/settings.py

Also rename local database to dataservices.
Wellicht moeten sommige dingen to naar gisserver. 
Maar voorlopig werkt dit wel.

Add authorization to WFS views

---

src/dso_api/dynamic_api/fields.py
src/dso_api/dynamic_api/middleware.py
src/dso_api/dynamic_api/serializers.py
src/dso_api/dynamic_api/views.py
src/dso_api/settings.py
src/requirements.in
src/requirements.txt
src/rest_framework_dso/fields.py
src/rest_framework_dso/openapi.py
src/rest_framework_dso/serializers.py
src/rest_framework_dso/views.py
src/tests/conftest.py
src/tests/files/bagh.json
src/tests/test_dynamic_api/test_serializers.py
src/tests/test_dynamic_api/test_temporal_actions.py
src/tests/test_health.py

Allow time travel and filtering in API for certain datasets.
See https://github.com/Amsterdam/dso-api/pull/54/files#diff-e1d0622d4645aaddd417d53b52d575e2 
for examples of changes.

Temporal filtering

---

src/rest_framework_dso/filters.py
src/tests/test_dynamic_api/test_filters.py

Fixing error filtering NULL end dates.

Fixing error in Range filter.

---

src/requirements.in
src/requirements.txt

Bump schematools to 0.8.11

---

src/dso_api/dynamic_api/views.py
src/requirements.in
src/requirements.txt
src/rest_framework_dso/crs.py
src/rest_framework_dso/views.py

* expand parameter
* pagination 5000 (onderdeel van server)
* CSV export

WFS improvements

---

docs/Dockerfile

Proper location for docs.

---

src/rest_framework_dso/fields.py

[DS-325] bugfix
[DS-325]: https://datapunt.atlassian.net/browse/DS-325

[DS-325] bug

---

Jenkinsfile

Restart nginx after doing magic.

Restart nginx.

---

src/dso_api/dynamic_api/remote/serializers.py
src/dso_api/dynamic_api/remote/views.py
src/rest_framework_dso/serializers.py
src/tests/files/brp.json
src/tests/test_dynamic_api/remote/test_views.py

...schema is also updated in another repo

Fix BRP required message

---

src/dso_api/dynamic_api/exceptions.py
src/dso_api/urls.py

Use X-Unique-ID passed by HAProxy as instance value

Format 500 (and other) errors according to DSO-API standards

---

src/dso_api/dynamic_api/permissions.py
src/dso_api/dynamic_api/serializers.py
src/dso_api/settings.py
src/requirements.in
src/requirements.txt
src/tests/conftest.py
src/tests/test_dynamic_api/test_serializers.py
src/tests/test_dynamic_api/test_views.py

Adding profile based authorization and field mutations to DSO API.

Profile based authorization and field mutations

---

src/dso_api/dynamic_api/serializers.py
src/rest_framework_dso/fields.py
src/rest_framework_dso/utils.py
src/tests/conftest.py
src/tests/files/gebieden.json
src/tests/test_dynamic_api/test_views.py

Mogelijkheid tot embedding (_expand en _expandScope) toegevoegd voor NM-relaties.

Add embedding for NM related fields

---

src/dso_api/dynamic_api/middleware.py
src/dso_api/settings.py
src/requirements.in
src/requirements.txt
src/tests/test_dynamic_api/test_views.py

Log following on every request:
- Username (if available)
- Request Path
- Request Parameters
- Request Headers

Audit logging

---

.pre-commit-config.yaml
src/.jenkins/owasp_vulnerability_scan/owasp_scan.py
src/dso_api/dynamic_api/app_config.py
src/dso_api/dynamic_api/locking.py
src/dso_api/dynamic_api/remote/views.py
src/dso_api/urls.py
src/requirements_dev.txt
src/rest_framework_dso/openapi.py
src/rest_framework_dso/utils.py
src/tests/conftest.py
src/tests/test_dynamic_api/remote/test_views.py
src/tests/test_dynamic_api/test_filters.py
src/tests/test_dynamic_api/test_serializers.py
src/tests/test_dynamic_api/test_views.py
src/tests/test_rest_framework_dso/test_serializers.py

Fixed code to use a particular black version,
so there is no disagreement between various installs.

Fixed black formatting and pre-commit config

---

src/dso_api/dynamic_api/app_config.py
src/dso_api/dynamic_api/fields.py
src/dso_api/dynamic_api/serializers.py
src/rest_framework_dso/fields.py
src/tests/conftest.py
src/tests/files/woningbouwplannen.json
src/tests/test_dynamic_api/test_views.py

For a non-temporal dataset containing a many-to-many relation to a temporal dataset.

Loose nm temporal

---

.github/pull_request_template.md
DEVELOPMENT.md
README.md

- Improved Development documentation
- Pull Request template

Development doc.

---

Jenkinsfile
README.md
src/.jenkins/openapi_validator/Dockerfile
src/.jenkins/openapi_validator/docker-compose.yml
src/.jenkins/openapi_validator/run_validator.sh
src/requirements.in
src/requirements.txt
src/requirements_dev.txt
src/rest_framework_dso/openapi.py

OpenAPI spec and extra step in Jenkins that will validate spec.

Fixed OpenAPI spec and added jenkins validator.

---

src/.jenkins/openapi_validator/docker-compose.yml

Fixes pipeline for openapi validator.

Fix volumes bug in openapi validator.

---

src/dso_api/dynamic_api/serializers.py

This avoids finding out which fields are loose M2M relations each loop.
When a full export is done (e.g. 50.000 items), this also called `toCamelCase()` 100.000 times.

Optimize loose M2M field collection, called during each loop

---

src/dso_api/dynamic_api/filterset.py
src/dso_api/dynamic_api/middleware.py
src/dso_api/dynamic_api/serializers.py
src/rest_framework_dso/filters.py
src/rest_framework_dso/renderers.py
src/tests/test_dynamic_api/test_views_api.py
src/tests/test_rest_framework_dso/test_filters.py

(see commit titles)
* Better error messages on schema errors
* fix middleware for profiling (assign new attributes earlier)
* optimizations

Various export fixes

---

src/dso_api/dynamic_api/remote/views.py

API KEY is not a keyfile

---

src/requirements.in
src/requirements.txt

Version bump schematools to 0.17.4

---

src/dso_api/dynamic_api/serializers.py
src/tests/test_dynamic_api/test_views_api.py

It rendered `{volgnummer}=field_in_camel_case`

Bugfixes for _links section

---

docs/source/generic/rest.rst
docs/source/generic/temporele_datasets.rst

Examples from the documentation updated with the current DSO/HAL specification.

doc examples updated to HAL specs

---

src/dso_api/dynamic_api/views/wfs.py
src/tests/test_dynamic_api/test_views_wfs.py

Fixes issue with WFS authorization.

camelCase Auth checks in WFS.

---

src/tests/test_rest_framework_dso/test_views.py

Fix test failure

---

src/dso_api/dynamic_api/fields.py
src/dso_api/dynamic_api/serializers.py
src/requirements.in
src/rest_framework_dso/fields.py

Renaming confusing method name in order to give more clarity (and allow get_dataset method to be added in future).

Rename DynamicModel.get_dataset into DynamicModel.get_dataset_schema for clarity

---

docs/source/_templates/datasets/dataset.rst.j2
docs/source/datasets.py

added table description to docs

---

src/requirements.in
src/requirements.txt

requirements changes

---

src/requirements.txt

changed requirements

---

src/requirements.in
src/requirements.txt

requirements.in, requirements.txt
NA
NA
NA

requirement changes

---

dev-docs/source/api/schematools.contrib.django.models.rst
dev-docs/source/conf.py

In addition:
- added support for Googel Style docstrings (napoleon extension)
- fix double mention of `Profile.get_permissions`

Stricter ref checking in Sphinx based dev docs.

---

docs/source/generic/mvt.rst
docs/source/index.rst
src/dso_api/dynamic_api/urls.py
src/dso_api/dynamic_api/views/__init__.py
src/dso_api/dynamic_api/views/mvt.py
src/requirements.in
src/requirements.txt
src/templates/dso_api/dynamic_api/mvt_index.html
src/tests/test_dynamic_api/test_views_mvt.py

Mapbox Vector Tiles (MVT) support

---

src/dso_api/dynamic_api/openapi.py
src/dso_api/dynamic_api/permissions.py
src/dso_api/dynamic_api/routers.py
src/dso_api/urls.py
src/rest_framework_dso/renderers.py
src/tests/test_dynamic_api/test_openapi.py
src/tests/test_openapi.py

This splits the OpenAPI per dataset.

Split OpenAPI pages per dataset

---

src/dso_api/dynamic_api/openapi.py
src/dso_api/settings.py
src/rest_framework_dso/openapi.py

More fixes after the Django 3.1 / drf-spectacular upgrade done in https://github.com/Amsterdam/dso-api/compare/ab6f4c00e3601d553b7c3ca7f4a3fbc0dbedb569..bba94c8c1578f9d5c83f690fa8288aba1867deb1

OpenAPI fixes with latest drf-spectacular

---

src/dso_api/dynamic_api/remote/views.py

HTTP pooling for the hcbrk endpoint. The pool is initialized in a separate function and the check on the endpoint URL now checks in the hostname only.

Move HTTP pool logic into a new function

---

dev-docs/source/auth.rst

dev-docs. I added a small script to make JWTs for communicating with the API.
Putting code in the docs is a hack. When I tried to turn this into a management command, I found that it had to create the entire suite of viewsets, didn't work when the server wasn't running locally and was terribly slow.

Example script for using JWK's in dev-docs

---

src/dso_api/dynamic_api/permissions.py

Fixes: https://sentry.data.amsterdam.nl/sentry/datapunt-apis-prod/issues/2695029/?environment=dso-api
Error above is pretty much edge case: happened when DB was refreshed.
However there are other cases (remote APIs) where this error can happen again.

QuickFix: TableScopes defaults corrected.

---

docs/source/_templates/datasets/dataset.rst.j2
docs/source/_templates/wfs-datasets/dataset.rst.j2
docs/source/datasets.py

* Fix GeoJSON / CSV export links
* Sync operator list for supported lookups

User-documentation fixes

---

src/dso_api/dynamic_api/fields.py
src/dso_api/dynamic_api/serializers.py
src/tests/test_dynamic_api/test_serializers.py
src/tests/test_dynamic_api/test_views_api.py

* Hide title when the model doesn't have a display field
* Hide null values and empty M2M lists.

Fix _links section, hide useless title and null links

---

dev-docs/source/environment.rst
src/dso_api/settings.py

Add missing logger and remove unnecessary handlers.

---

docker-compose.yml
src/dso_api/settings.py

Fixing logging. Commit message sucks.

---

src/dso_api/dynamic_api/serializers.py
src/rest_framework_dso/embedding.py
src/rest_framework_dso/serializers.py
src/tests/test_dynamic_api/test_serializers.py
src/tests/test_dynamic_api/test_views_api.py

max embed level was accidentally too low for testing purposes.
Also improved error message.

AB#8160 Fix/eager loading error

---

src/requirements.in
src/requirements.txt

Fixes mypy issues.
Diff: https://github.com/tfranzel/drf-spectacular/compare/0.15.0...0.17.1

Upgrade drf-spectacular

---

src/dso_api/dynamic_api/remote/clients.py
src/tests/conftest.py
src/tests/files/hcbrk.json
src/tests/test_dynamic_api/remote/test_views.py

It was completely broken, but I didn't notice because I was running the integration tests with the wrong envvars and didn't see that they were being skipped. The endpoint isn't in use because its authorization code isn't ready yet.

[AB#6571] Fix HCBRK remote client and add tests

---

src/tests/test_dynamic_api/remote/test_views.py

Only adds coverage of existing functionality. `test_remote_detail_view_with_profile_scope` now fails when I comment out the line
headers["Authorization"] = auth
in the AuthForwardingClient.

AB#8005 Improve auth test for BRP client

---

src/dso_api/dynamic_api/middleware.py
src/dso_api/dynamic_api/permissions.py
src/requirements.in
src/requirements.txt
src/tests/conftest.py
src/tests/test_dynamic_api/test_serializers.py
src/tests/utils.py

Uses Amsterdam/schema-tools#174.

Use new UserScopes object with explicit scopes

---

src/dso_api/dynamic_api/views/api.py

Replaces the filter info with a link to the docs.

AB#11746 Remove the unneeded text above the API, and redirect to the docs

---

src/dso_api/dynamic_api/views/mvt.py

The get_geo_tables function would list a dataset twice if it had two geo fields.

List datasets once in MVT dataset view

---

src/dso_api/dynamic_api/fields.py
src/dso_api/dynamic_api/serializers.py
src/dso_api/dynamic_api/utils.py
src/dso_api/dynamic_api/views/api.py
src/requirements.in
src/requirements.txt
src/rest_framework_dso/embedding.py
src/rest_framework_dso/serializers.py
src/tests/conftest.py
src/tests/files/gebieden.json
src/tests/test_dynamic_api/test_serializers.py
src/tests/test_dynamic_api/test_views_api.py

See explanation about this PR in the commit message.

AB#4378 show temporal in relations

---

src/rest_framework_dso/filters/lookups.py

Following a discussion on Teams.

Comment on the strange looking IsEmpty filter

---

docs/source/_templates/datasets/dataset.rst.j2
docs/source/datasets.py
docs/source/generic/rest.rst

* Betere algemene uitleg
* Toont volledige lijst van filters inclusief operators
* Betere toelichting per operator

Improve documentation on available filters in the REST API

---

src/requirements.in
src/requirements.txt

Bump schematools to 0.23.2

---

src/dso_api/dynamic_api/remote/views.py
src/tests/test_dynamic_api/remote/test_views.py

Hotfix. Will restore a sanitized version of the detailed error in a later commit.

AB#6554 Don't leak responses from remotes to unauthorized clients

---

src/dso_api/dynamic_api/remote/views.py
src/tests/test_dynamic_api/remote/test_views.py

AB#6554 Log sanitized version of remote serializer errors

---

docs/source/datasets.py
src/requirements.in
src/requirements.txt

File has been renamed in schematools from `schema_from_url`
to `dataset_schema_from_url`.

Change file import from schematools

---

dev-docs/source/auth.rst
dev-docs/source/howto/install.rst
src/dso_api/dynamic_api/remote/clients.py
src/dso_api/dynamic_api/remote/views.py

Final step of the rename. Also cleans up some of the validation code.

Drop hcbrk in favor of haalcentraalbrk

---

docs/source/datasets.py
docs/source/generic/rest.rst
src/dso_api/dynamic_api/filterset.py
src/dso_api/dynamic_api/routers.py
src/dso_api/dynamic_api/serializers.py
src/requirements.in
src/requirements.txt
src/tests/test_dynamic_api/test_views_api.py

Can be merged when https://github.com/Amsterdam/schema-tools/pull/189 is released

Catch-up DSO-API with new schematools API's and fix for unwanted M2M relations

---

src/dso_api/dynamic_api/serializers.py

Instead collect everything in a single SerializerAssemblyLine class.
This also streamlines how both 'fields' and 'new_attrs' has to be set.

Refactor serializer factory logic to avoid passing many out-variables to functions

---

src/dso_api/dynamic_api/remote/clients.py

To debug the response time issues with HCBRK.

Log response times from remotes

---

src/dso_api/dynamic_api/openapi.py
src/dso_api/dynamic_api/remote/clients.py
src/rest_framework_dso/parsers.py
src/rest_framework_dso/views.py

This is supported as of Django 2.2 :-)

Replace request.META with request.headers (by django-upgrade)

---

.github/workflows/build-aks-image.yml

Introducing automatic trigger of Azure pipeline when master is updated.

Az pipelines

---

src/requirements.in
src/requirements.txt

Bump schematools from 1.0.1 to 1.0.2

Bump schematools from 1.0.1 to 1.0.2

---

dev-docs/source/environment.rst

Extra details on APP Insights querying.

Additional information on how to query AppInsights.

---

src/dso_api/dynamic_api/serializers.py
src/rest_framework_dso/serializers.py

Addressing feedback for PR #364

Improve serializer docs

---

docs/Makefile
docs/source/_templates/datasets/dataset.rst.j2
docs/source/_templates/wfs-datasets/dataset.rst.j2
docs/source/datasets.py

Fixed the appearance of `frozenset({...})` in the HTML, and also brushed up the expand/embed appearance.

Docs: fix auth and expand appearance

---

src/dso_api/dynamic_api/remote/views.py
src/dso_api/dynamic_api/views/api.py
src/rest_framework_dso/renderers.py
src/templates/dso_api/dynamic_api/api.html

* DynamicViewSet classes and factories
* Browsable API Renderer
* Browsable API template
fixes [AB#21617](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/21617) [AB#21618](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/21618)
The idea for the pagination in the template is that we only show all the pages when the payload includes a count, this in order to avoid doing a count on every request.

AB#21617 AB#21618 Browsable API improvements

---

src/dso_api/dynamic_api/filterset.py
src/dso_api/settings.py
src/dso_api/urls.py
src/rest_framework_dso/filters/filtersets.py
src/tests/conftest.py
src/tests/files/bag.json
src/tests/test_dynamic_api/test_filters.py

* filterset_factory
NOTE that the openapi docs are still not correctly picking up the filter. I will do that in a follow-up PR.

AB#11748 Dotted filter syntax on subfields

---

src/dso_api/urls.py

Only add static routes in DEBUG mode

---

src/dso_api/dynamic_api/filterset.py

The previous code suppressed all ValueErrors instead of just the specific one indicating "no subfields on this field".
As a result, invalid filters were silently ignored, leading to `[gt]`, `[lt]`, `[gte]` and `[lte]` filters not being executed.

Don't suppress all ValueErrors in filterset_factory

---

docs/source/datasets.py
src/dso_api/dynamic_api/filterset.py
src/dso_api/dynamic_api/remote/serializers.py
src/requirements.in
src/requirements.txt
src/tests/utils.py

Change the spelling of "subfield" globally too.

Upgrade to schema-tools 3.0.0

---

src/dso_api/dynamic_api/filterset.py
src/dso_api/dynamic_api/middleware.py
src/dso_api/settings.py
src/rest_framework_dso/filters/filters.py

Some stuff I found while going through the codebase. See commit messages for details.

Minor cleanups

---

src/tests/files/unconventional_temporal.json

check in test fixture

---

src/dso_api/dynamic_api/fields.py
src/dso_api/dynamic_api/serializers.py
src/rest_framework_dso/embedding.py
src/rest_framework_dso/fields.py
src/rest_framework_dso/serializers.py
src/tests/conftest.py
src/tests/test_dynamic_api/test_serializers.py
src/tests/test_dynamic_api/test_views_api.py

HyperLinkedTemporalSerializerField
fixes [AB#20770](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/20770)

AB#20770 Add  { fk_name: fk_value } to _links 

---

docs/source/datasets.py

This fix works around the fact that `table.fields` also returns mangled subfields. It's using `get_fields(include_subfields=False)` instead, and resolves the field names itself.
Then changed `_filter_payload()` to generate the filter name itself, without using the mangled subfields name.

Fix showing subfield incorrectly in filter documentation

---

src/dso_api/dynamic_api/permissions.py
src/tests/test_dynamic_api/test_views_api.py

AB#24404 Fix filter auth on relations with non-composite keys

---

src/dso_api/dynamic_api/remote/clients.py

URL path may contain sensitive data. Also removed the reason from error messages.

Log only the host from the remotes

---

src/dso_api/dynamic_api/permissions.py
src/dso_api/dynamic_api/views/api.py
src/tests/test_dynamic_api/test_request_validation.py
src/tests/test_dynamic_api/test_views_api.py

Filter validation+authorization now happens in DynamicApiViewSet.initial, much earlier in the call chain.
The check still lives in permissions.py, which may not be right place for it.

AB#24404 AB#24678 Filter validation

---

Jenkinsfile
src/.jenkins/test/test.sh

Get fresh network names on Jenkins

---

src/dso_api/dynamic_api/management/commands/dump_serializers.py
src/dso_api/dynamic_api/serializers.py

Just like `manage.py dump_models` we now have `manage.py dump_serializers`.

Added dump_serializers command for debugging

---

src/tests/test_rest_framework_dso/test_views.py

Amends 451e7973a599db967469889c065518ebeb726ffc

Fixed previous commit, code review changes were not tested

---

src/dso_api/dynamic_api/views/index.py

Previously, any error would give a 500 on /v1/. Any breakage now causes a dataset to be skipped in the listing.

Handle broken datasets gracefully on /v1/

---

src/dso_api/dynamic_api/views/index.py

Forgot to commit the final version before push.

Handle broken datasets gracefully on /v1/, now for real

---

dev-docs/source/howto/install.rst
src/dso_api/dynamic_api/permissions.py
src/dso_api/dynamic_api/remote/clients.py
src/dso_api/settings.py
src/tests/conftest.py
src/tests/files/haalcentraalbag/amstel1.json
src/tests/files/haalcentraalbag/schema.json
src/tests/test_dynamic_api/remote/test_views.py

Also includes changes to Haal Centraal BRK, which shares code with BAG.

AB#25901 Proxy for Haal Centraal BAG

---

src/Dockerfile

For debugging purposes and health checks it is useful to have curl
> * Tests
>

Install curl in the Docker container

---

src/Dockerfile

Install curl in the runtime image, not in the tmp builder

---

dev-docs/source/auth.rst
src/dso_api/dynamic_api/management/commands/maketoken.py

Script taken from the readthedocs (courtesy lbam).

Add the `maketoken` script as Django mgm. command

---

src/rest_framework_dso/views.py

This isn't doing anything and is making refactoring harder.

[AB#27822] Remove Accept-CRS requirement stub

---

src/tests/test_dynamic_api/test_filters.py

Forgot to do this in 1eb24bd20c9a9e3688298cc5815a25d9c5de6c10.

[AB#27822] Remove ignored headers kwarg from test

---

src/dso_api/urls.py
src/tests/test_health.py

As a kind of reverse health check.

Add simple check to trigger 500 errors

---

Jenkinsfile

Testing Jenkins without docs image. Needs to be pulled into master for proper testing (with revert afterward).

[TEST] Don't deploy docs image

---

Jenkinsfile

This reverts commit d304e6131ac51d32a77ff9a9912afedeb99b1323.

Revert "Don't deploy docs image (#487)"

---

docs/source/datasets.py

additionalFilters has already been removed from the schemas that used it.

Don't use deprecated schema-tools functionality in docs

---

src/dso_api/dynamic_api/permissions.py
src/requirements.in
src/requirements.txt
src/tests/test_dynamic_api/test_request_validation.py

This is part of the filter refactor. It also fixes a bug in the relation auth checking.

Fix relation auth check and tests (AB#24838)

---

src/tests/test_dynamic_api/test_views_wfs.py

Security hardening: this works, but wasn't tested.

Test WFS filter authorization (AB#25950)

---

src/dso_api/dynamic_api/remote/clients.py

Resolves one TODO item for cheap.

HC-BRK no longer has the separate /adressen/zoek endpoint

---

src/dso_api/dynamic_api/management/commands/dump_serializers.py

cleanup dump_serializers code

---

src/dso_api/dynamic_api/filterset.py
src/dso_api/dynamic_api/serializers.py
src/dso_api/dynamic_api/views/mvt.py
src/dso_api/dynamic_api/views/wfs.py

Removes use of deprecated function

Use the new DynamicModel.get_field_schema() logic from schematools

---

docker-compose.yml
src/dso_api/dynamic_api/management/commands/implement_constraint.py

Tested locally on a fresh import of tables from schemas.data.amsterdam.nl

One-off management command for adding constraint

---

src/requirements.in

For [AB#44268](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/44268).

Upgrade schema-tools to 3.6.0

---

.pre-commit-config.yaml
src/.jenkins/owasp_vulnerability_scan/owasp_scan.py
src/dso_api/settings.py

Also fixes both of the issues that it found. Neither has high priority.
See commit messages for details.

Bandit (security scan) pre-commit hook

---

docs/source/generic/rest.rst
docs/source/generic/rest/authorization.rst

For end-users.
Left out the e-mail address for IV Beheer, because these
docs are spambot-accessible.
> * Tests
>

AB#28851 Add documentation about authorization

---

docs/source/generic/rest/authorization.rst

Describe what happens when a scope does not apply. Mostly a translation of the English description in the dev docs.

Expand authorization users docs further

---

src/dso_api/settings.py

The log level was set to the wrong environment variable.

Fix audit log configuration

---

src/dso_api/dynamic_api/remote/clients.py

We now pass on all filters for BAG to Haal Centraal, while still only allowing some filters for BRK, because the latter allows searching on BSN even within tables that do not contain a BSN field.

Quick fix for haalcentraal/bag/addresseerbareobjecten

---

docs/source/datasets.py
src/dso_api/dynamic_api/filters/parser.py

Also fix the error message in case no filters are defined for a field type.

[AB#50110] Add filter support for generic Geometry fields.

---

src/tests/conftest.py
src/tests/files/haalcentraalbag/0123456789123456.json
src/tests/files/haalcentraalbag/schema.json
src/tests/test_dynamic_api/remote/test_views.py

For [AB#50368](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/50368).

Fix HCBAG remote to accept HC's actual output

---

src/dso_api/dynamic_api/openapi.py
src/tests/test_dynamic_api/test_openapi.py

For [AB#50780](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/50780)
Ref https://swagger.io/specification/#license-object

Fix license field in OpenAPI output

---

src/dso_api/dynamic_api/routers.py

One to_snake_case call down, many more to go.

Clean up URL construction in dynamic_api.routers

---

src/requirements.in
src/requirements.txt

This improves response writing and reduces output size.

Bump django-gisserver to include its performance improvements

---

src/dso_api/dynamic_api/filters/parser.py

Amends: e5a5fcefb73b94ebe1e8993c019aa22d4a0eeaed / PR #568

Fix missing to_snake_case() for temporal filtering on loose relations

---

src/dso_api/dynamic_api/filters/parser.py

Requests such as
/v1/meldingen/statistieken/?buurt.identificatie[like]=X
would give error 500 due to Django not being able to handle them. Give a 400 instead.

Give 400 instead of 500 for "Related Field got invalid lookup"

---

src/dso_api/dynamic_api/serializers/factories.py
src/dso_api/dynamic_api/serializers/fields.py
src/dso_api/settings.py
src/requirements.in
src/requirements.txt
src/tests/conftest.py
src/tests/settings.py
src/tests/test_dynamic_api/test_serializers.py

Reverts #129. We're going to do this another way.

Remove stale Azure Blob Storage support

---

docs/source/datasets.py

This leverages the fact that `dataset_schemas_from_schemas_path` and `dataset_schemas_from_url` now return the paths.

Fix docs/source/datasets.py to work with new schema-tools

---

src/dso_api/dynamic_api/management/commands/dump_serializers.py

Fixed logic that accessed app labels/models for remote viewsets Also fixed showing "Manager at 0xaddress"

Fix dump_serializers output, which crashed for remote viewsets

---

src/dso_api/dynamic_api/routers.py
src/dso_api/dynamic_api/views/__init__.py
src/dso_api/dynamic_api/views/doc.py
src/templates/dso_api/dynamic_api/docs/dataset_wfs.html

Still needs some fixing and polishing, but the bulk is there.

Generate WFS dataset HTML docs

---

src/dso_api/settings.py
src/get_imds_db_token.sh

in stead of assigning it in a background job :D

fix imds token script

---

src/dso_api/dynamic_api/views/doc.py
src/templates/dso_api/dynamic_api/docs/dataset.html
src/templates/dso_api/dynamic_api/docs/dataset_wfs.html
src/templates/dso_api/dynamic_api/docs/overview.html

Copy-pasted from the dataset query UI, so everything looks similar.
Still figuring out how to style the Markdown-generated docs.

Prettify generated docs with CSS

---

Jenkinsfile

Fixes mistake from previous commit.

Remove remnant of doc container

---

src/dso_api/dynamic_api/serializers/factories.py

Remove "brk" from shortnames hack

---

src/tests/test_dynamic_api/test_views_api.py

Fixes [AB#64216](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/64216).

Test _expandScope with array-typed relation

---

src/requirements.in
src/requirements.txt

For [AB#66611](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/66611).

Upgrade drf_spectacular

---

src/dso_api/dynamic_api/filters/openapi.py

Fixes [AB#66611](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/66611).

Add temporal dimensions to OpenAPI schemas

---

src/dso_api/dynamic_api/views/doc.py

Else, all lowercase titles follow all uppercase titles (A-Za-z).

Docs: sort datasets by lowercase title

---

src/dso_api/dynamic_api/views/mvt.py

In particular, ziektePlagenExotenGroen did not work. Code mostly copy-pasted from WFS.

Fix MVT for datasets with funny names

---

src/dso_api/dynamic_api/remote/clients.py
src/dso_api/dynamic_api/remote/views.py

See commit messages for details.

Restore HTTP error handling for haalcentraal/bag + further refactor of Haal Centraal client

---

src/dso_api/dynamic_api/remote/views.py

For Haal Centraal BRK, we need something more general, because its output can contain both absolute and relative URLs, and we need to rewrite both.

Generalize _rewrite_links in remote.views

---

src/requirements.in
src/requirements.txt
src/requirements_dev.txt

Bump Django

---

src/dso_api/dynamic_api/openapi.py

The spec for BAG takes 5.7s to construct on my laptop, and is 1.81 MB large. Using gzip_page compresses it down to 86 kB, or a factor 21 smaller. Caching it means it gets loaded instantly the second time.
Added Vary header so only json requests are cached.

Compress and cache OpenAPI specs (#714)

---

src/dso_api/dynamic_api/views/doc.py

Fixes [AB#44403](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/44403).

Display temporal dimensions in dataset docs

---

src/requirements.in
src/requirements.txt
src/requirements_dev.txt

Will write a unit test for a separate PR.

Bump schema-tools to get security fix for array fields

---

src/tests/conftest.py
src/tests/files/datasets/array_auth.json
src/tests/test_dynamic_api/test_views_api.py

Regression test, fixes [AB#73289](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/73289).

Test auth on array of nested objects

---

src/rest_framework_dso/renderers.py

When rendering a dict, we've already checked if it's empty, so we can save a single yield by putting the `'{'` in the first separator.
Also, the `level` variable can be a boolean, because we only increment it and check for zero. I didn't benchmark this, but we've had a case before (Amsterdam/django-gisserver#11) where just keeping track of a count inside serialization code caused a 5% throughput drop.

Tiny optimizations for HAL-JSON rendering

---

src/dso_api/dynamic_api/views/mvt.py
src/tests/test_dynamic_api/test_views_mvt.py

This should alleviate some of the memory problems of our MVT endpoints, by simply not sending non-geo fields' data at high zoom levels. The cutoff point is hardcoded, based on some experimentation with MVT maps. At level 15, street names should be legible and the city of Amsterdam consists of many separate tiles, so the load of serving it can be spread among DSO-API instances.
For [AB#61546](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/61546).

MVT: less detail at higher zoom levels

---

src/requirements.txt
src/requirements_dev.txt

Forgot to run `make requirements`.

Add datadiensten-apikeyclient to requirement

---

src/templates/dso_api/dynamic_api/api.html
src/templates/dso_api/dynamic_api/docs/overview.html

Add this notification to the opening page of the APIs.

AB#87406 Add notification about the introduction of the API keys.

---

src/dso_api/static/dso_api/dynamic_api/css/browsable_api.css
src/requirements.in
src/templates/dso_api/dynamic_api/api.html

And pin apikey middleware to latest version.

AB#90859 Update API Key server banner text

---

src/requirements.in
src/requirements.txt
src/requirements_dev.txt

To get the fix to set the display field correctly.

bump schematools to 5.23.1

---

src/requirements.in
src/requirements.txt
src/requirements_dev.txt

schema-tools bump to 5.23.4

---

src/dso_api/dynamic_api/views/doc.py
src/dso_api/settings.py
src/templates/dso_api/dynamic_api/docs/gis/index.md

fix links for gis docs
add settings based dynamic link for keys server
[AB#106692](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/106692)
[AB#106760](https://dev.azure.com/CloudCompetenceCenter/089b38ee-0066-4b66-a36c-20744a0e4348/_workitems/edit/106760)

Robbie/fix docs links AB#106692 & AB#106760

---

src/dso_api/settings.py

This breaks tests during deploy pipeline.

Fix issue with line length in settings.py

---

src/dso_api/dynamic_api/temporal.py

added to_snake_case to temporal ordering fields

---

src/dso_api/dbroles.py

Fixed is_internal to allow for .amsterdam.nl subdomains. 

---

src/dso_api/dynamic_api/views/doc.py

the snake bites again

---

src/dso_api/settings.py

Fixed bulk export endpoint. And made it configurable with variable

Make bulk export endpoint variable

---

src/dso_api/dynamic_api/openapi.py

fixed docs links for datasets with a number

---

.github/dependabot.yml

Create dependabot yml file configuring dependabot for weekly updates. It should run pip compile, update all packages and create a PR.

Let dependabot check for package updates

---

.github/dependabot.yml

Fix whitespace problem to please pre-commit hooks

Fix whitespace problem

---

src/templates/dso_api/dynamic_api/api.html

updated jquery version

---

src/dso_api/dynamic_api/views/doc.py
src/tests/test_dynamic_api/test_doc.py

updated doc.py to only show table defined exports

---

src/dso_api/settings.py

Add OAUTH_JWKS_URLS setting to allow both Entra ID and Keyclock tokens

---

src/dso_api/dynamic_api/filters/lookups.py

fixed in SQL syntax for not lookup

---

src/dso_api/dynamic_api/filters/lookups.py

update not operator sql query

---

src/dso_api/static/dso_api/dynamic_api/js/browsable_api.js

The newly created option element should be selected.

Make operator option element selected

---

src/Dockerfile

Updated python image to debian 12

---

src/dso_api/dbroles.py

A temporary solution to allow external accounts to be used. It should be removed after 2025-05-20.

added penttest emails for ey

---

src/dso_api/dynamic_api/views/doc.py
src/templates/dso_api/dynamic_api/docs/dataset.html

cleaned up description for downloadble exports

---

src/dso_api/dbroles.py

EY email addresses that were added for the pentest can be removed after 2025-05-20.

removed ey email addresses (DO NOT MERGE BEFORE 2025-05-20)

---

.github/workflows/build-aks-image.yml

removed akscluster parameter from pipeline target, but CI workflow was not updated yet  
tested and working

debug deploy trigger

---

src/rest_framework_dso/renderers.py
src/tests/test_dynamic_api/views/test_api_formats.py

Fix rendering ArrayField values in the CSV export

---

src/requirements.in
src/requirements.txt
src/requirements_dev.txt
src/rest_framework_dso/views.py
src/templates/dso_api/dynamic_api/docs/gis/manual.md
src/templates/dso_api/dynamic_api/docs/gis/qgis.md
src/templates/dso_api/dynamic_api/docs/rest/formats.md
src/templates/dso_api/dynamic_api/docs/rest/projections.md
src/tests/test_dynamic_api/views/test_api_formats.py

Fix axis ordering.
Documented axis ordering.
and included some extra bits I'd already written.

Update django-gisserver for axis ordering and add documentation

---

src/dso_api/dbroles.py
src/dso_api/dynamic_api/management/commands/implement_constraint.py
src/dso_api/settings.py
src/requirements.in
src/requirements.txt
src/requirements_dev.txt
src/tests/conftest.py
src/tests/settings.py

(can be merged after schematools has a new release, and is bumped in the requirements)

Use psycopg3 for database connections

---

src/requirements.in
src/requirements.txt
src/requirements_dev.txt

update schematools to 8.2.2

---

src/requirements.in
src/requirements.txt
src/requirements_dev.txt

bump schematools to v8.2.2.post1

---

src/requirements.in
src/requirements.txt
src/requirements_dev.txt

Update schema tools to fix issues with percent signs in db comments

Update schema tools
